#!/usr/bin/env python3
"""Write batched official-food upsert SQL from the CSVs.

Does not connect to a database and does not accept a database URL. Apply the
generated files yourself, foods batches before alias batches. The default
output directory is /tmp and the files are not committed.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

_SPEC = importlib.util.spec_from_file_location(
    "official_foods_import",
    Path(__file__).resolve().parent / "import.py",
)
if _SPEC is None or _SPEC.loader is None:
    raise RuntimeError("could not load import.py")
_IMPORT = importlib.util.module_from_spec(_SPEC)
sys.modules[_SPEC.name] = _IMPORT
_SPEC.loader.exec_module(_IMPORT)

FOOD_COLUMNS = ("food_code",) + _IMPORT.FOOD_UPDATE_COLUMNS
FOOD_ASSIGNMENTS = ", ".join(
    f"{column} = excluded.{column}" for column in _IMPORT.FOOD_UPDATE_COLUMNS
)
ALIAS_COLUMNS = (
    "food_code",
    "alias",
    "reading",
    "normalized",
    "priority",
    "note",
    "source",
    "is_candidate",
    "candidate_rank",
)


def sql_text(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_number(value: float) -> str:
    text = format(value, ".15g")
    if "e" in text or "E" in text:
        text = format(value, "f").rstrip("0").rstrip(".")
    return text


def sql_scalar(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return sql_number(value)
    if isinstance(value, int):
        return str(value)
    return sql_text(str(value))


def sql_food_value(column: str, value: object) -> str:
    if column == "raw_values":
        if value is None:
            return "'{}'::jsonb"
        return sql_text(str(value)) + "::jsonb"
    if column == "estimated_fields":
        items = value or []
        if not items:
            return "'{}'::text[]"
        return (
            "ARRAY["
            + ", ".join(sql_text(str(item)) for item in items)
            + "]::text[]"
        )
    return sql_scalar(value)


def _batches(rows: list[str], batch_size: int) -> list[list[str]]:
    return [rows[index : index + batch_size] for index in range(0, len(rows), batch_size)]


def _write_batch(path: Path, statement: str) -> None:
    path.write_text(
        "\n".join(
            [
                "-- Generated by tool/official_foods/export_sql.py. Do not edit by hand.",
                "set standard_conforming_strings = on;",
                "begin;",
                statement.rstrip(),
                "commit;",
                "",
            ]
        ),
        encoding="utf-8",
    )


def write_foods(rows: list[dict[str, str]], out_dir: Path, batch_size: int) -> list[Path]:
    # Last CSV row for a food_code wins, matching a sequential upsert.
    by_code: dict[str, dict[str, str]] = {}
    order: list[str] = []
    for row in rows:
        code = row["food_code"].strip()
        if code not in by_code:
            order.append(code)
        by_code[code] = row
    tuples = []
    for code in order:
        payload = _IMPORT.food_payload(by_code[code])
        literals = [
            sql_food_value(column, value)
            for column, value in zip(FOOD_COLUMNS, payload, strict=True)
        ]
        tuples.append("(" + ", ".join(literals) + ", now())")
    paths = []
    for index, batch in enumerate(_batches(tuples, batch_size), start=1):
        path = out_dir / f"01_official_foods_{index:04d}.sql"
        statement = (
            "insert into public.official_foods ("
            + ", ".join(FOOD_COLUMNS)
            + ", imported_at)\nvalues\n  "
            + ",\n  ".join(batch)
            + "\non conflict (food_code) do update\nset "
            + FOOD_ASSIGNMENTS
            + ", imported_at = now();"
        )
        _write_batch(path, statement)
        paths.append(path)
    return paths


def write_aliases(
    rows: list[dict[str, str]],
    present: set[str],
    out_dir: Path,
    batch_size: int,
) -> tuple[list[Path], int]:
    prepared, skipped = _IMPORT.prepare_aliases(rows, present)
    # Sequential upserts keep the last row for (food_code, normalized).
    # One INSERT cannot update that key twice, so collapse before batching.
    collapsed: dict[tuple[str, str], dict] = {}
    order: list[tuple[str, str]] = []
    for item in prepared:
        key = (item["code"], item["normalized"])
        if key not in collapsed:
            order.append(key)
        collapsed[key] = item
    tuples = []
    for key in order:
        item = collapsed[key]
        values = [
            item["code"],
            item["alias"],
            item["reading"],
            item["normalized"],
            item["priority"],
            item["note"],
            item["source"],
            item["is_candidate"],
            item["candidate_rank"],
        ]
        literals = [sql_scalar(value) for value in values]
        tuples.append("(" + ", ".join(literals) + ")")
    paths = []
    if not tuples:
        return paths, skipped
    assignments = """
alias = excluded.alias,
reading = excluded.reading,
priority = excluded.priority,
note = excluded.note,
source = excluded.source,
is_candidate = excluded.is_candidate,
candidate_rank = excluded.candidate_rank
""".strip()
    for index, batch in enumerate(_batches(tuples, batch_size), start=1):
        path = out_dir / f"02_official_food_aliases_{index:04d}.sql"
        statement = (
            "insert into public.official_food_aliases ("
            + ", ".join(ALIAS_COLUMNS)
            + ")\nvalues\n  "
            + ",\n  ".join(batch)
            + "\non conflict (food_code, normalized) do update\nset "
            + assignments
            + ";"
        )
        _write_batch(path, statement)
        paths.append(path)
    return paths, skipped


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--foods", type=Path, required=True)
    parser.add_argument("--aliases", type=Path, required=True)
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("/tmp/official-foods-sql"),
        help="Directory for generated SQL batches (not committed)",
    )
    parser.add_argument("--batch-size", type=int, default=100)
    args = parser.parse_args(argv)
    if args.batch_size < 1:
        raise SystemExit("--batch-size must be at least 1")

    foods = _IMPORT._read_csv(args.foods)
    aliases = _IMPORT._read_csv(args.aliases)
    present = {row["food_code"].strip() for row in foods}
    args.out_dir.mkdir(parents=True, exist_ok=True)
    food_paths = write_foods(foods, args.out_dir, args.batch_size)
    alias_paths, skipped = write_aliases(aliases, present, args.out_dir, args.batch_size)
    print(
        f"wrote foods_batches={len(food_paths)} alias_batches={len(alias_paths)} "
        f"skipped_aliases={skipped} dir={args.out_dir}"
    )
    for path in food_paths + alias_paths:
        print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
