#!/bin/sh
# Generates ios/Flutter/GoogleSignIn.generated.xcconfig from GOOGLE_IOS_CLIENT_ID.
#
# Usage (either):
#   GOOGLE_IOS_CLIENT_ID=xxxx.apps.googleusercontent.com ./tool/configure_google_signin_ios.sh
#   ./tool/configure_google_signin_ios.sh   # reads tool/dart_defines.local.json if present
#
# The reversed client ID is required for Google Sign-In URL scheme on iOS.
# Do not commit the generated xcconfig (see .gitignore).

set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
OUTPUT_FILE="${ROOT_DIR}/ios/Flutter/GoogleSignIn.generated.xcconfig"
LOCAL_DEFINES="${ROOT_DIR}/tool/dart_defines.local.json"

read_json_value() {
  key="$1"
  file="$2"
  python3 - "$key" "$file" <<'PY'
import json, sys
key, path = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    value = data.get(key, "")
    if value is None:
        value = ""
    print(value)
except FileNotFoundError:
    print("")
PY
}

CLIENT_ID="${GOOGLE_IOS_CLIENT_ID:-}"
SERVER_CLIENT_ID="${GOOGLE_WEB_CLIENT_ID:-}"

if [ -z "$CLIENT_ID" ] && [ -f "$LOCAL_DEFINES" ]; then
  CLIENT_ID="$(read_json_value "GOOGLE_IOS_CLIENT_ID" "$LOCAL_DEFINES")"
fi

if [ -z "$SERVER_CLIENT_ID" ] && [ -f "$LOCAL_DEFINES" ]; then
  SERVER_CLIENT_ID="$(read_json_value "GOOGLE_WEB_CLIENT_ID" "$LOCAL_DEFINES")"
fi

if [ -z "$CLIENT_ID" ]; then
  cat > "$OUTPUT_FILE" <<'EOF'
// GOOGLE_IOS_CLIENT_ID is not set. Google Sign-In URL scheme is not configured.
GID_CLIENT_ID=
GID_SERVER_CLIENT_ID=
GOOGLE_REVERSED_CLIENT_ID=
EOF
  echo "Wrote ${OUTPUT_FILE} (empty — set GOOGLE_IOS_CLIENT_ID to enable Google Sign-In on iOS)."
  exit 0
fi

# 逆順 ID（com.googleusercontent.apps.…）、バンドル ID、カンマ区切りは不可。
if ! printf %s "$CLIENT_ID" | grep -Eq '^[0-9]+-[0-9a-z]+\.apps\.googleusercontent\.com$'; then
  echo "error: GOOGLE_IOS_CLIENT_ID は 123-abc.apps.googleusercontent.com の形にしてください（Google Cloud の iOS クライアントの「クライアント ID」）" >&2
  exit 1
fi
if [ -n "$SERVER_CLIENT_ID" ] &&
  ! printf %s "$SERVER_CLIENT_ID" | grep -Eq '^[0-9]+-[0-9a-z]+\.apps\.googleusercontent\.com$'; then
  echo "error: GOOGLE_WEB_CLIENT_ID は 123-abc.apps.googleusercontent.com の形にしてください（Web クライアントの「クライアント ID」）" >&2
  exit 1
fi
if [ -n "$SERVER_CLIENT_ID" ] && [ "${CLIENT_ID%%-*}" != "${SERVER_CLIENT_ID%%-*}" ]; then
  echo "error: GOOGLE_IOS_CLIENT_ID と GOOGLE_WEB_CLIENT_ID が別の Google Cloud プロジェクトのものです（先頭の数字が違う）。同じプロジェクトの iOS と Web を使ってください" >&2
  exit 1
fi

PREFIX="${CLIENT_ID%.apps.googleusercontent.com}"
REVERSED="com.googleusercontent.apps.${PREFIX}"

cat > "$OUTPUT_FILE" <<EOF
// Generated by tool/configure_google_signin_ios.sh — do not commit.
GID_CLIENT_ID=${CLIENT_ID}
GID_SERVER_CLIENT_ID=${SERVER_CLIENT_ID}
GOOGLE_REVERSED_CLIENT_ID=${REVERSED}
EOF

echo "Wrote ${OUTPUT_FILE}"
