/// events_catalog.csv と一致するイベント名と、許す属性名。
abstract final class AnalyticsEventNames {
  static const List<String> all = [
    'app_install_first_open',
    'app_open',
    'app_foreground',
    'app_background',
    'session_start',
    'session_end',
    'app_version_changed',
    'screen_view',
    'tab_select',
    'analytics_consent_shown',
    'login_tap',
    'login_result',
    'logout',
    'onboarding_step_view',
    'onboarding_step_complete',
    'onboarding_complete',
    'first_meal_guide_shown',
    'first_meal_guide_finished',
    'health_permission_result',
    'health_integration_changed',
    'health_sync_result',
    'food_search',
    'food_search_result_select',
    'food_entry_added',
    'food_entry_updated',
    'food_entry_deleted',
    'food_entry_restored',
    'food_memo_saved',
    'recent_foods_open',
    'barcode_scan_open',
    'barcode_scan_result',
    'barcode_lookup_result',
    'saved_food_created',
    'saved_food_updated',
    'saved_food_deleted',
    'public_food_published',
    'public_food_duplicate_warning',
    'public_food_search_quota',
    'public_food_rated',
    'public_food_reported',
    'food_creator_blocked',
    'meal_template_saved',
    'meal_template_deleted',
    'meal_template_applied',
    'official_food_detail_view',
    'exercise_search',
    'exercise_search_result_select',
    'exercise_entry_added',
    'exercise_entry_updated',
    'exercise_entry_deleted',
    'exercise_entry_restored',
    'workout_template_saved',
    'workout_template_deleted',
    'custom_activity_saved',
    'weight_entry_added',
    'weight_entry_updated',
    'alcohol_entry_added',
    'alcohol_entry_changed',
    'goal_updated',
    'landing_guidance_shown',
    'landing_guidance_tap',
    'profile_updated',
    'settings_changed',
    'history_day_selected',
    'legal_document_view',
    'contact_tap',
    'widget_tap',
    'widget_registration_imported',
    'widget_config_saved',
    'widget_presence',
    'siri_request_started',
    'siri_prompt',
    'siri_request_finished',
    'siri_registration_imported',
    'siri_open_search',
    'coach_proposal_shown',
    'coach_proposal_registered',
    'share_tap',
    'announcement_read',
    'review_prompt_shown',
    'review_prompt_answer',
    'paywall_open',
    'paywall_close',
    'plan_select',
    'purchase_tap',
    'purchase_result',
    'restore_tap',
    'restore_result',
    'gate_shown',
    'gate_tap',
    'entitlement_observed',
    'apple_ads_attribution',
    'app_error',
    'sync_failure',
    'local_data_cleared',
    'analytics_queue_health',
    'account_deletion_started',
  ];

  static const Map<String, Set<String>> allowedProps = {
    'app_install_first_open': {'original_purchase_date', 'original_app_version', 'app_transaction_environment'},
    'app_open': {'launch_source', 'previous_session_abnormal_end'},
    'app_foreground': {'background_seconds'},
    'app_background': {'foreground_seconds', 'current_screen', 'current_screen_dwell_ms'},
    'session_start': {'session_number', 'gap_seconds'},
    'session_end': {'duration_seconds', 'screens_viewed', 'events_count'},
    'app_version_changed': {'from_app_version', 'to_app_version', 'from_os_version', 'to_os_version'},
    'screen_view': {'screen', 'previous_screen', 'previous_screen_dwell_ms', 'via'},
    'tab_select': {'tab', 'from_tab'},
    'analytics_consent_shown': {'policy_version', 'surface'},
    'login_tap': {'provider'},
    'login_result': {'provider', 'result', 'error_kind', 'is_new_account'},
    'logout': {'forced'},
    'onboarding_step_view': {'step'},
    'onboarding_step_complete': {'step', 'duration_ms', 'skipped'},
    'onboarding_complete': {'goal_type', 'health_enabled', 'duration_ms'},
    'first_meal_guide_shown': {},
    'first_meal_guide_finished': {'action'},
    'health_permission_result': {'context', 'granted'},
    'health_integration_changed': {'enabled', 'context'},
    'health_sync_result': {'trigger', 'result', 'workouts_imported', 'weight_samples_imported', 'duration_ms'},
    'food_search': {'source', 'query', 'query_length', 'result_count', 'latency_ms'},
    'food_search_result_select': {'source', 'position', 'result_count', 'query_length', 'item_kind'},
    'food_entry_added': {'food_entry_ids', 'method', 'meal_group', 'items_count'},
    'food_entry_updated': {'food_entry_id', 'changed_fields', 'source_choice'},
    'food_entry_deleted': {'food_entry_id', 'undo_offered'},
    'food_entry_restored': {'food_entry_id'},
    'food_memo_saved': {'food_entry_id', 'has_memo', 'memo_length'},
    'recent_foods_open': {'is_plus'},
    'barcode_scan_open': {},
    'barcode_scan_result': {'method', 'result', 'duration_ms'},
    'barcode_lookup_result': {'result', 'http_status', 'latency_ms'},
    'saved_food_created': {'saved_food_id', 'visibility', 'from'},
    'saved_food_updated': {'saved_food_id', 'visibility', 'changed_fields'},
    'saved_food_deleted': {'saved_food_id'},
    'public_food_published': {'saved_food_id', 'action'},
    'public_food_duplicate_warning': {'kind', 'choice'},
    'public_food_search_quota': {'remaining', 'limit', 'is_plus'},
    'public_food_rated': {'saved_food_id', 'rating'},
    'public_food_reported': {'saved_food_id', 'reason'},
    'food_creator_blocked': {'action'},
    'meal_template_saved': {'template_id', 'action', 'items_count', 'template_count_after'},
    'meal_template_deleted': {'template_id'},
    'meal_template_applied': {'template_id', 'items_count', 'food_entry_ids'},
    'official_food_detail_view': {'official_food_code'},
    'exercise_search': {'source', 'query', 'query_length', 'result_count'},
    'exercise_search_result_select': {'source', 'position', 'result_count'},
    'exercise_entry_added': {'exercise_entry_ids', 'method', 'items_count'},
    'exercise_entry_updated': {'exercise_entry_id', 'changed_fields'},
    'exercise_entry_deleted': {'exercise_entry_id', 'undo_offered'},
    'exercise_entry_restored': {'exercise_entry_id'},
    'workout_template_saved': {'template_id', 'action', 'items_count', 'template_count_after'},
    'workout_template_deleted': {'template_id'},
    'custom_activity_saved': {},
    'weight_entry_added': {'weight_entry_id', 'source'},
    'weight_entry_updated': {'weight_entry_id', 'action'},
    'alcohol_entry_added': {'alcohol_entry_id'},
    'alcohol_entry_changed': {'alcohol_entry_id', 'action'},
    'goal_updated': {'source', 'target_mode', 'changed_fields'},
    'landing_guidance_shown': {'guidance_kind'},
    'landing_guidance_tap': {'action'},
    'profile_updated': {'changed_fields', 'source'},
    'settings_changed': {'setting_key', 'new_value'},
    'history_day_selected': {'days_ago'},
    'legal_document_view': {'document'},
    'contact_tap': {'channel'},
    'widget_tap': {'surface', 'slot', 'kind', 'result', 'template_id', 'registration_id'},
    'widget_registration_imported': {'registration_id', 'food_entry_ids', 'exercise_entry_ids', 'delay_seconds'},
    'widget_config_saved': {'assigned_meal_slots', 'assigned_exercise_slots', 'surface'},
    'widget_presence': {'home_widget_count', 'lock_widget_count'},
    'siri_request_started': {'intent', 'has_parameter'},
    'siri_prompt': {'request_id', 'prompt_kind', 'answered'},
    'siri_request_finished': {'request_id', 'status', 'stop_reason', 'prompts_count', 'duration_ms', 'items_count', 'registration_id', 'continued_in_app'},
    'siri_registration_imported': {'registration_id', 'food_entry_ids', 'exercise_entry_ids', 'undo', 'delay_seconds'},
    'siri_open_search': {'reason'},
    'coach_proposal_shown': {'coach_proposal_log_id', 'proposals_count'},
    'coach_proposal_registered': {'coach_proposal_log_id', 'food_entry_ids'},
    'share_tap': {'card', 'result', 'activity_type'},
    'announcement_read': {'announcement_id'},
    'review_prompt_shown': {'trigger'},
    'review_prompt_answer': {'answer'},
    'paywall_open': {'entry_point', 'products_loaded', 'load_error'},
    'paywall_close': {'dwell_ms', 'last_selected_product_id', 'purchased'},
    'plan_select': {'product_id'},
    'purchase_tap': {'product_id', 'price_display', 'currency', 'entry_point'},
    'purchase_result': {'product_id', 'status', 'error_code', 'is_trial', 'offer_type'},
    'restore_tap': {},
    'restore_result': {'result'},
    'gate_shown': {'feature', 'free_count'},
    'gate_tap': {'feature', 'choice'},
    'entitlement_observed': {'status', 'product_id', 'expires_at', 'original_transaction_id', 'changed'},
    'apple_ads_attribution': {'attribution', 'campaign_id', 'ad_group_id', 'keyword_id', 'ad_id', 'claim_type', 'conversion_type', 'click_date', 'country_or_region', 'supply_placement', 'org_id'},
    'app_error': {'error_type', 'where', 'fatal'},
    'sync_failure': {'table', 'step', 'error_kind', 'pending_count'},
    'local_data_cleared': {'reason', 'pending_records_count'},
    'analytics_queue_health': {'pending_count', 'oldest_pending_age_seconds', 'quarantined_count', 'dropped_overflow_count', 'native_pending_files', 'native_dropped_overflow_count', 'last_success_at'},
    'account_deletion_started': {'step'},
  };
}
