-- 家庭料理の型と入れ替え候補。official_foods が揃っているときだけ入れる。
-- アプリには埋め込まない。足すときは recipes.ts を編集し、この SQL を出し直す。
-- 本番には適用しない。

do $$
declare
  present integer;
begin
  select count(*) into present
  from public.official_foods
  where food_code in ('01026', '01039', '01064', '01088', '01128', '02017', '03003', '04032', '04033', '04039', '04046', '06049', '06061', '06065', '06103', '06153', '06182', '06223', '06226', '06233', '06245', '06264', '06267', '06291', '10134', '10263', '11019', '11115', '11220', '11224', '12004', '13040', '14002', '14006', '14017', '16025', '17007', '17012', '17015', '17028', '17045', '17063', '17138');
  if present < 43 then
    raise notice 'cook recipes skipped: official_foods has % of 43 codes', present;
    return;
  end if;

  delete from public.cook_recipes;

  insert into public.cook_recipes
    (id, name_template, genre, category, method, minutes, steps)
  values
    ('shoga', '{protein}の生姜焼き', '和', '主菜', '焼', 5, '["{protein}を一口大に切る。{ginger}{g:ginger}gを添える。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて2分絡め、中まで火を通す。","火を止めて器に盛る。"]'::jsonb),
    ('shoga-don', '{protein}の生姜焼き丼', '和', '丼麺', '焼', 5, '["{protein}を一口大に切る。{ginger}{g:ginger}gを添える。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて2分絡め、中まで火を通す。","{rice}{g:rice}gを器に盛り、具をのせる。"]'::jsonb),
    ('shoga-light', '{protein}の塩だれ焼き', '和', '主菜', '焼', 5, '["{protein}を一口大に切る。{ginger}{g:ginger}gを添える。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて2分絡め、中まで火を通す。","火を止めて器に盛る。","塩{g:salt}gを加えて味をととのえる。"]'::jsonb),
    ('miso-itame', '{protein}と{veg}の味噌炒め', '和', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分炒める。","{veg}と味噌{g:miso}gと砂糖{g:sugar}gと料理酒{g:sake}gを加えて2分炒め合わせる。","火を止めて器に盛る。"]'::jsonb),
    ('miso-don', '{protein}と{veg}の味噌炒め丼', '和', '丼麺', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分炒める。","{veg}と味噌{g:miso}gと砂糖{g:sugar}gと料理酒{g:sake}gを加えて2分炒め合わせる。","{rice}{g:rice}gを器に盛り、具をのせる。"]'::jsonb),
    ('soy-itame', '{protein}と{veg}の醤油炒め', '和', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('soy-rice', '{protein}と{veg}の醤油炒め丼', '和', '丼麺', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","{rice}{g:rice}gを器に盛り、具をのせる。"]'::jsonb),
    ('nikujaga', '肉じゃが', '和', '主菜', '煮', 11, '["{protein}とじゃがいも{g:potato}gと玉ねぎ{g:onion}gを食べる大きさに切る。","鍋に水を200mlと顆粒だし{g:dashi}gを入れ、{protein}を5分煮る。","じゃがいもと玉ねぎ、しょうゆ{g:soy}g、みりん{g:mirin}g、砂糖{g:sugar}gを加える。","弱火で6分煮て、じゃがいもに火を通す。"]'::jsonb),
    ('oyako', '親子丼', '和', '丼麺', '煮', 7, '["{protein}と玉ねぎ{g:onion}gを切る。","鍋に水を150mlと顆粒だし{g:dashi}g、しょうゆ{g:soy}g、みりん{g:mirin}gを入れて煮立たせる。","{protein}と玉ねぎを5分煮る。","卵{g:egg}gを回し入れ、ふたをして2分加熱してごはん{g:rice}gにのせる。"]'::jsonb),
    ('oyako-large', '大盛り親子丼', '和', '丼麺', '煮', 7, '["{protein}と玉ねぎ{g:onion}gを切る。","鍋に水を150mlと顆粒だし{g:dashi}g、しょうゆ{g:soy}g、みりん{g:mirin}gを入れて煮立たせる。","{protein}と玉ねぎを5分煮る。","卵{g:egg}gを回し入れ、ふたをして2分加熱してごはん{g:rice}gにのせる。"]'::jsonb),
    ('gyudon', '牛こま丼', '和', '丼麺', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加えて2分絡める。","ごはん{g:rice}gにのせてすぐに出す。"]'::jsonb),
    ('butadon', '豚こま丼', '和', '丼麺', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加えて2分絡める。","ごはん{g:rice}gにのせてすぐに出す。"]'::jsonb),
    ('chanchan', '鮭と{veg}のちゃんちゃん焼き', '和', '主菜', '焼', 8, '["鮭{g:protein}gと{veg}を食べやすく切る。","フライパンに鮭と{veg}、味噌{g:miso}g、砂糖{g:sugar}g、しょうゆ{g:soy}gを入れる。","ふたをして中火で6分焼く。","2分蒸らしてから器に盛る。"]'::jsonb),
    ('salmon-fry', '鮭と{veg}の味噌炒め', '和', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分炒める。","{veg}と味噌{g:miso}gと砂糖{g:sugar}gと料理酒{g:sake}gを加えて2分炒め合わせる。","火を止めて器に盛る。"]'::jsonb),
    ('salmon-rice', '鮭の焼き丼', '和', '丼麺', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加えて2分絡める。","ごはん{g:rice}gにのせてすぐに出す。"]'::jsonb),
    ('nanban', '{protein}の南蛮漬け', '和', '主菜', '焼', 6, '["{protein}と玉ねぎ{g:onion}gを食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gで{protein}を4分焼く。","酢{g:vinegar}gとしょうゆ{g:soy}gと砂糖{g:sugar}gを混ぜ、2分漬けてなじませる。","玉ねぎを添えて器に盛る。"]'::jsonb),
    ('steam-rice', '{protein}のレンジ蒸し丼', '和', '丼麺', '蒸', 6, '["{protein}を食べやすく切り、耐熱皿に並べる。","しょうゆ{g:soy}gとみりん{g:mirin}gと塩{g:salt}gをふる。","電子レンジで4分加熱し、取り出して2分蒸らす。","中まで火が通ったことを確かめる。","{rice}{g:rice}gと一緒に器へ盛る。"]'::jsonb),
    ('steam-plate', '{protein}の塩蒸し', '和', '主菜', '蒸', 6, '["{protein}を食べやすく切り、耐熱皿に並べる。","しょうゆ{g:soy}gとみりん{g:mirin}gと塩{g:salt}gをふる。","電子レンジで4分加熱し、取り出して2分蒸らす。","中まで火が通ったことを確かめる。","器に盛ってすぐに出す。"]'::jsonb),
    ('miso-soup-tofu', '木綿豆腐と{veg}の味噌汁', '和', '汁物', '煮', 7, '["鍋に水を300mlと顆粒だし{g:dashi}gを入れて中火にする。","{protein}と{veg}を鍋に入れる。5分煮る。","味噌{g:miso}gを溶き入れ、しょうゆ{g:soy}gを足して2分煮て火を止める。","器に注いですぐに出す。"]'::jsonb),
    ('miso-soup-pork', '{protein}の味噌汁', '和', '汁物', '煮', 7, '["鍋に水を300mlと顆粒だし{g:dashi}gを入れて中火にする。","{protein}を鍋に入れる。5分煮る。","味噌{g:miso}gを溶き入れ、しょうゆ{g:soy}gを足して2分煮て火を止める。","器に注いですぐに出す。"]'::jsonb),
    ('hiyayakko', '冷奴', '和', '副菜', '和え', 5, '["絹ごし豆腐{g:tofu}gを器に出す。","しょうゆ{g:soy}gをかけ、しょうが{g:ginger}gをのせる。","冷蔵庫で5分冷やし、味を見て出す。"]'::jsonb),
    ('ohitashi-leaf', '{veg}のおひたし', '和', '副菜', '和え', 5, '["{veg}を鍋で3分ゆでて、水気をよく切る。","しょうゆ{g:soy}gと顆粒だし{g:dashi}gを和える。","2分置いて味を含ませてから器に盛る。"]'::jsonb),
    ('cabbage-ae', '{veg}の和え物', '和', '副菜', '和え', 5, '["{veg}を食べやすく切り、塩{g:salt}gをふる。","しょうゆ{g:soy}gと酢{g:vinegar}gと砂糖{g:sugar}gを和える。","5分置いて味がなじんだら器に盛る。"]'::jsonb),
    ('cucumber-ae', 'きゅうりの和え物', '和', '副菜', '和え', 5, '["{veg}を食べやすく切り、塩{g:salt}gをふる。","しょうゆ{g:soy}gと酢{g:vinegar}gと砂糖{g:sugar}gを和える。","5分置いて味がなじんだら器に盛る。"]'::jsonb),
    ('potato-butter', '{veg}のバター蒸し', '和', '軽い品', '蒸', 6, '["{veg}を洗って耐熱皿に乗せる。","電子レンジで4分加熱する。","バター{g:butter}gと塩{g:salt}gをのせ、こしょう{g:pepper}gを振る。","2分置いて熱いうちに出す。"]'::jsonb),
    ('tamago', '卵焼き', '和', '軽い品', '焼', 5, '["卵{g:egg}gを溶き、塩{g:salt}gとこしょう{g:pepper}gを加える。","フライパンを中火にし、{oil}{g:oil}gを熱する。","溶き卵を流して3分焼く。","2分待って形が固まったら器に盛る。"]'::jsonb),
    ('tamago-veg', '卵と{veg}の炒め', '和', '主菜', '炒', 6, '["卵{g:egg}gを溶き、塩{g:salt}gとこしょう{g:pepper}gを加える。","フライパンを中火にし、{oil}{g:oil}gを熱する。","{veg}を先に1分炒めてから、溶き卵を流して3分焼く。","2分待って形が固まったら器に盛る。"]'::jsonb),
    ('tamago-gohan', '卵かけご飯', '和', '丼麺', '蒸', 5, '["{rice}{g:rice}gを器に盛る。","卵{g:egg}gを落とし、しょうゆ{g:soy}gをかける。","電子レンジで2分加熱する。","3分置いて火が通ったら出す。","塩{g:salt}gを加えて味をととのえる。"]'::jsonb),
    ('natto-gohan', '納豆和えご飯', '和', '丼麺', '和え', 5, '["{rice}{g:rice}gに{protein}{g:protein}gをのせる。","しょうゆ{g:soy}gをかけて混ぜる。","電子レンジで2分加熱する。","3分置いてから出す。","塩{g:salt}gを加えて味をととのえる。"]'::jsonb),
    ('udon', '{protein}と{veg}の煮込みうどん', '和', '丼麺', '煮', 7, '["鍋に水を300mlと顆粒だし{g:dashi}gを入れて中火にする。","{protein}と{veg}を鍋に入れる。5分煮る。","味噌{g:miso}gを溶き入れ、しょうゆ{g:soy}gを足して2分煮て火を止める。","{rice}{g:rice}gを入れて器に注ぐ。"]'::jsonb),
    ('soba', '{protein}とねぎの煮込みそば', '和', '丼麺', '煮', 7, '["鍋に水を300mlと顆粒だし{g:dashi}gを入れて中火にする。","{protein}と{veg}を鍋に入れる。5分煮る。","味噌{g:miso}gを溶き入れ、しょうゆ{g:soy}gを足して2分煮て火を止める。","{rice}{g:rice}gを入れて器に注ぐ。"]'::jsonb),
    ('chahan', '{protein}チャーハン', '中', '丼麺', '炒', 5, '["{protein}を小さく切り、卵{g:egg}gを溶いておく。","フライパンを中火にし、{oil}{g:oil}gで{protein}を2分炒める。","卵とごはん{g:rice}gを加えて3分炒め、しょうゆ{g:soy}gと塩{g:salt}gで味をつける。","パラッとしたら火を止めて器に盛る。"]'::jsonb),
    ('chahan-veg', '{protein}と{veg}の炒飯', '中', '丼麺', '炒', 5, '["{protein}と{veg}を小さく切り、卵{g:egg}gを溶いておく。","フライパンを中火にし、{oil}{g:oil}gで{protein}を2分炒める。","卵とごはん{g:rice}gを加えて3分炒め、しょうゆ{g:soy}gと塩{g:salt}gで味をつける。","パラッとしたら火を止めて器に盛る。"]'::jsonb),
    ('mapo', '麻婆豆腐', '中', '主菜', '炒', 7, '["木綿豆腐{g:tofu}gと{protein}を食べやすく切る。","フライパンにごま油{g:oil}gを熱し、{protein}とねぎ{g:negi}gを3分炒める。","豆腐と水を50ml、しょうゆ{g:soy}gと味噌{g:miso}gと砂糖{g:sugar}gを加えて4分煮る。","とろみがついたら器に盛る。"]'::jsonb),
    ('mapo-don', '麻婆豆腐丼', '中', '丼麺', '炒', 7, '["木綿豆腐{g:tofu}gと{protein}を食べやすく切る。","フライパンにごま油{g:oil}gを熱し、{protein}とねぎ{g:negi}gを3分炒める。","豆腐と水を50ml、しょうゆ{g:soy}gと味噌{g:miso}gと砂糖{g:sugar}gを加えて4分煮る。","とろみがついたらごはん{g:rice}gにのせる。"]'::jsonb),
    ('hoikoro', '{protein}と{veg}の細切り炒め', '中', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('subuta', '酢豚', '中', '主菜', '炒', 6, '["{protein}と玉ねぎ{g:onion}gを食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gで{protein}を4分焼く。","酢{g:vinegar}gとしょうゆ{g:soy}gと砂糖{g:sugar}gを混ぜ、2分漬けてなじませる。","玉ねぎを添えて器に盛る。"]'::jsonb),
    ('tomato-egg', 'トマトと卵の炒め', '中', '主菜', '炒', 6, '["卵{g:egg}gを溶き、塩{g:salt}gとこしょう{g:pepper}gを加える。","フライパンを中火にし、{oil}{g:oil}gを熱する。","{veg}を先に1分炒めてから、溶き卵を流して3分焼く。","2分待って形が固まったら器に盛る。"]'::jsonb),
    ('tomato-egg-rice', 'トマトと卵の炒め丼', '中', '丼麺', '炒', 6, '["卵{g:egg}gを溶き、塩{g:salt}gとこしょう{g:pepper}gを加える。","フライパンを中火にし、{oil}{g:oil}gを熱する。","{veg}を先に1分炒めてから、溶き卵を流して3分焼く。","2分待って形が固まったら器に盛る。"]'::jsonb),
    ('chinjao', '{protein}とピーマンの炒め', '中', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('moyashi-pork', '{protein}ともやしの炒め', '中', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('hakusai-pork', '{protein}と白菜のうま煮', '中', '主菜', '煮', 10, '["{protein}と{veg}を食べやすく切る。","鍋に水を200mlと顆粒だし{g:dashi}gを入れて中火で煮立たせる。","{protein}を入れて6分煮て、しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加える。","弱火で4分煮て、具に味を含ませる。"]'::jsonb),
    ('tofu-stir', '木綿豆腐と{veg}の炒め', '中', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('garlic-chicken', '{protein}のにんにく炒め', '中', '主菜', '炒', 5, '["{protein}を一口大に切る。{ginger}{g:ginger}gを添える。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて2分絡め、中まで火を通す。","火を止めて器に盛る。"]'::jsonb),
    ('egg-drop', 'かきたま汁', '中', '汁物', '煮', 7, '["鍋に水を300mlと顆粒だし{g:dashi}gを入れて中火にする。","{protein}を鍋に入れる。5分煮る。","味噌{g:miso}gを溶き入れ、しょうゆ{g:soy}gを足して2分煮て火を止める。","器に注いですぐに出す。"]'::jsonb),
    ('tuna-cabbage', 'ツナとキャベツの和風パスタ', '洋', '丼麺', '炒', 9, '["スパゲティ{g:pasta}gを湯で6分ゆでる。","フライパンで{oil}{g:oil}gを熱し、{protein}と{veg}を2分炒める。","しょうゆ{g:soy}gとこしょう{g:pepper}gを加えて1分絡める。","ゆでたスパゲティを戻し入れて火を通し、器に盛る。"]'::jsonb),
    ('tuna-tomato', 'ツナとトマトのパスタ', '洋', '丼麺', '炒', 9, '["スパゲティ{g:pasta}gを湯で6分ゆでる。","フライパンで{oil}{g:oil}gを熱し、{protein}と{veg}を2分炒める。","しょうゆ{g:soy}gとこしょう{g:pepper}gを加えて1分絡める。","ゆでたスパゲティを戻し入れて火を通し、器に盛る。"]'::jsonb),
    ('salmon-pasta', '鮭とほうれん草のパスタ', '洋', '丼麺', '炒', 9, '["スパゲティ{g:pasta}gを湯で6分ゆでる。","フライパンで{oil}{g:oil}gを熱し、{protein}と{veg}を2分炒める。","しょうゆ{g:soy}gとこしょう{g:pepper}gを加えて1分絡める。","ゆでたスパゲティを戻し入れて火を通し、器に盛る。"]'::jsonb),
    ('chicken-tomato', '{protein}のトマト煮', '洋', '主菜', '煮', 10, '["{protein}と{veg}を食べやすく切る。","鍋に水を200mlと顆粒だし{g:dashi}gを入れて中火で煮立たせる。","{protein}を入れて6分煮て、しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加える。","弱火で4分煮て、具に味を含ませる。"]'::jsonb),
    ('chicken-tomato-rice', '{protein}のトマト煮丼', '洋', '丼麺', '煮', 10, '["{protein}と{veg}を食べやすく切る。","鍋に水を200mlと顆粒だし{g:dashi}gを入れて中火で煮立たせる。","{protein}を入れて6分煮て、しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加える。","弱火で4分煮て、具に味を含ませる。","{rice}{g:rice}gにのせる。"]'::jsonb),
    ('omelette', 'オムレツ', '洋', '主菜', '焼', 5, '["卵{g:egg}gを溶き、塩{g:salt}gとこしょう{g:pepper}gを加える。","フライパンを中火にし、{oil}{g:oil}gを熱する。","溶き卵を流して3分焼く。","2分待って形が固まったら器に盛る。"]'::jsonb),
    ('omelette-veg', '{veg}のオムレツ', '洋', '主菜', '焼', 6, '["卵{g:egg}gを溶き、塩{g:salt}gとこしょう{g:pepper}gを加える。","フライパンを中火にし、{oil}{g:oil}gを熱する。","{veg}を先に1分炒めてから、溶き卵を流して3分焼く。","2分待って形が固まったら器に盛る。"]'::jsonb),
    ('hamburger', '{protein}のハンバーグ', '洋', '主菜', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{onion}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('saute', '{protein}のソテー', '洋', '主菜', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて2分絡め、中まで火を通す。","火を止めて器に盛る。","塩{g:salt}gを加えて味をととのえる。"]'::jsonb),
    ('saute-veg', '{protein}と{veg}のソテー', '洋', '主菜', '焼', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('gratin-toast', 'ツナトースト', '洋', '軽い品', '焼', 5, '["食パン{g:bread}gに{protein}をのせる。","フライパンを弱火にし、バター{g:butter}gで2分焼く。","塩{g:salt}gとこしょう{g:pepper}gを振る。","3分加熱して中まで温まったら皿に出す。"]'::jsonb),
    ('cheese-toast', 'チーズトースト', '洋', '軽い品', '焼', 5, '["食パン{g:bread}gに{protein}をのせる。","フライパンを弱火にし、バター{g:butter}gで2分焼く。","塩{g:salt}gとこしょう{g:pepper}gを振る。","3分加熱して中まで温まったら皿に出す。"]'::jsonb),
    ('egg-bread', '卵の焼きトースト', '洋', '主食', '焼', 5, '["食パン{g:bread}gに{protein}をのせる。","フライパンを弱火にし、バター{g:butter}gで2分焼く。","塩{g:salt}gとこしょう{g:pepper}gを振る。","3分加熱して中まで温まったら皿に出す。"]'::jsonb),
    ('potato-salad', 'じゃがいもの和え物', '洋', '副菜', '和え', 5, '["{veg}を食べやすく切り、塩{g:salt}gをふる。","しょうゆ{g:soy}gと酢{g:vinegar}gと砂糖{g:sugar}gを和える。","5分置いて味がなじんだら器に盛る。"]'::jsonb),
    ('broccoli-ae', 'ブロッコリーの和え物', '洋', '副菜', '和え', 5, '["{veg}を食べやすく切り、塩{g:salt}gをふる。","しょうゆ{g:soy}gと酢{g:vinegar}gと砂糖{g:sugar}gを和える。","5分置いて味がなじんだら器に盛る。"]'::jsonb),
    ('minestrone', 'トマトスープ', '洋', '汁物', '煮', 7, '["鍋に水を300mlと顆粒だし{g:dashi}gを入れて中火にする。","{protein}と{veg}を鍋に入れる。5分煮る。","味噌{g:miso}gを溶き入れ、しょうゆ{g:soy}gを足して2分煮て火を止める。","器に注いですぐに出す。"]'::jsonb),
    ('creamless-stew', '{protein}とじゃがいもの煮込み', '洋', '主菜', '煮', 11, '["{protein}とじゃがいも{g:potato}gと玉ねぎ{g:onion}gを食べる大きさに切る。","鍋に水を200mlと顆粒だし{g:dashi}gを入れ、{protein}を5分煮る。","じゃがいもと玉ねぎ、しょうゆ{g:soy}g、みりん{g:mirin}g、砂糖{g:sugar}gを加える。","弱火で6分煮て、じゃがいもに火を通す。"]'::jsonb),
    ('fish-meuniere', '鮭のムニエル', '洋', '主菜', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて2分絡め、中まで火を通す。","火を止めて器に盛る。","塩{g:salt}gを加えて味をととのえる。"]'::jsonb),
    ('garlic-tomato', '{protein}とトマトのにんにく炒め', 'エスニック', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。{ginger}{g:ginger}gを添える。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('garlic-cabbage', '{protein}とキャベツのにんにく炒め', 'エスニック', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。{ginger}{g:ginger}gを添える。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('ethnic-veg', '{protein}と{veg}のエスニック炒め', 'エスニック', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分炒める。","{veg}と味噌{g:miso}gと砂糖{g:sugar}gと料理酒{g:sake}gを加えて2分炒め合わせる。","火を止めて器に盛る。"]'::jsonb),
    ('ethnic-soup', '{protein}とトマトのスープ', 'エスニック', '汁物', '煮', 7, '["鍋に水を300mlと顆粒だし{g:dashi}gを入れて中火にする。","{protein}と{veg}を鍋に入れる。5分煮る。","味噌{g:miso}gを溶き入れ、しょうゆ{g:soy}gを足して2分煮て火を止める。","器に注いですぐに出す。"]'::jsonb),
    ('ethnic-don', '{protein}のトマト丼', 'エスニック', '丼麺', '煮', 10, '["{protein}と{veg}を食べやすく切る。","鍋に水を200mlと顆粒だし{g:dashi}gを入れて中火で煮立たせる。","{protein}を入れて6分煮て、しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加える。","弱火で4分煮て、具に味を含ませる。","{rice}{g:rice}gにのせる。"]'::jsonb),
    ('chicken-broccoli', '鶏むね肉とブロッコリーの甘辛炒め', '洋', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。","砂糖{g:sugar}gを加えて味をととのえる。"]'::jsonb),
    ('chicken-broccoli-any', '{protein}とブロッコリーの炒め', '洋', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('low-oil-chicken', '{protein}と{veg}の蒸し炒め', '和', '主菜', '蒸', 6, '["{protein}を食べやすく切り、耐熱皿に並べる。","しょうゆ{g:soy}gとみりん{g:mirin}gと塩{g:salt}gをふる。","電子レンジで4分加熱し、取り出して2分蒸らす。","{veg}を添える。","器に盛ってすぐに出す。"]'::jsonb),
    ('hearty-don', '{protein}と卵の丼', '和', '丼麺', '焼', 5, '["{protein}を小さく切り、卵{g:egg}gを溶いておく。","フライパンを中火にし、{oil}{g:oil}gで{protein}を2分炒める。","卵とごはん{g:rice}gを加えて3分炒め、しょうゆ{g:soy}gと塩{g:salt}gで味をつける。","パラッとしたら火を止めて器に盛る。"]'::jsonb),
    ('pork-cabbage-rice', '豚こまとキャベツの丼', '和', '丼麺', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{onion}を加えて{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","{rice}{g:rice}gを器に盛り、具をのせる。"]'::jsonb),
    ('chicken-onion-rice', '鶏むね肉と玉ねぎの丼', '和', '丼麺', '炒', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{onion}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","{rice}{g:rice}gを器に盛り、具をのせる。"]'::jsonb),
    ('chicken-spinach-rice', '鶏むね肉とほうれん草の丼', '和', '丼麺', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","{rice}{g:rice}gを器に盛り、具をのせる。"]'::jsonb),
    ('tofu-rice', '木綿豆腐の丼', '和', '丼麺', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加えて2分絡める。","ごはん{g:rice}gにのせてすぐに出す。"]'::jsonb),
    ('natto-egg-rice', '納豆と卵の丼', '和', '丼麺', '蒸', 5, '["{rice}{g:rice}gに{protein}{g:protein}gをのせる。","卵{g:egg}gを落とし、しょうゆ{g:soy}gをかける。","電子レンジで2分加熱する。","3分置いてから出す。","塩{g:salt}gを加えて味をととのえる。"]'::jsonb),
    ('salmon-cabbage-rice', '鮭とキャベツの丼', '和', '丼麺', '焼', 5, '["{protein}と{veg}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加えて2分絡める。","ごはん{g:rice}gにのせてすぐに出す。"]'::jsonb),
    ('cabbage-egg', 'キャベツと卵の炒め', '和', '軽い品', '炒', 6, '["卵{g:egg}gを溶き、塩{g:salt}gを加える。","フライパンを中火にし、{oil}{g:oil}gを熱する。","{veg}を先に1分炒めてから、溶き卵を流して3分焼く。","2分待って形が固まったら器に盛る。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて味をととのえる。"]'::jsonb),
    ('chicken-potato', '鶏むね肉とじゃがいもの煮物', '和', '主菜', '煮', 11, '["{protein}とじゃがいも{g:potato}gと玉ねぎ{g:onion}gを食べる大きさに切る。","鍋に水を200mlと顆粒だし{g:dashi}gを入れ、{protein}を5分煮る。","じゃがいもと玉ねぎ、しょうゆ{g:soy}g、みりん{g:mirin}g、砂糖{g:sugar}gを加える。","弱火で6分煮て、じゃがいもに火を通す。"]'::jsonb),
    ('many-bowl', '鶏むね肉とキャベツの丼', '和', '丼麺', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","卵{g:egg}gを流し入れて火を通す。","{rice}{g:rice}gを器に盛り、具をのせる。"]'::jsonb),
    ('pork-only-rice', '豚こまの照り焼き丼', '和', '丼麺', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加えて2分絡める。","ごはん{g:rice}gにのせてすぐに出す。"]'::jsonb),
    ('avoid-oil-chicken', '鶏むね肉の煮丼', '和', '丼麺', '煮', 7, '["{protein}と玉ねぎ{g:onion}gを切る。","鍋に水を150mlと顆粒だし{g:dashi}g、しょうゆ{g:soy}g、みりん{g:mirin}gを入れて煮立たせる。","{protein}と玉ねぎを5分煮る。","卵{g:egg}gを回し入れ、ふたをして2分加熱してごはん{g:rice}gにのせる。"]'::jsonb),
    ('negi-salt', '{protein}のねぎ塩炒め', '和', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。","塩{g:salt}gを加えて味をととのえる。"]'::jsonb),
    ('chuka-don', '{protein}と{veg}の中華丼', '中', '丼麺', '焼', 5, '["{protein}と{veg}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gと砂糖{g:sugar}gを加えて2分絡める。","ごはん{g:rice}gにのせてすぐに出す。"]'::jsonb),
    ('yurinchi', '油淋鶏', '中', '主菜', '焼', 6, '["{protein}と玉ねぎ{g:onion}gを食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gで{protein}を4分焼く。","酢{g:vinegar}gとしょうゆ{g:soy}gと砂糖{g:sugar}gを混ぜ、2分漬けてなじませる。","玉ねぎを添えて器に盛る。"]'::jsonb),
    ('tofu-chuka', '木綿豆腐と{veg}の中華炒め', '中', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('negi-fry', '{protein}とねぎの炒め', '中', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('tuna-chuka', 'ツナと{veg}の中華炒め', '中', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('egg-tomato-soup', '{protein}とトマトのスープ', '中', '汁物', '煮', 7, '["鍋に水を300mlと顆粒だし{g:dashi}gを入れて中火にする。","{protein}と{veg}を鍋に入れる。5分煮る。","味噌{g:miso}gを溶き入れ、しょうゆ{g:soy}gを足して2分煮て火を止める。","器に注いですぐに出す。"]'::jsonb),
    ('chuka-steam', '{protein}の中華蒸し', '中', '主菜', '蒸', 6, '["{protein}を食べやすく切り、耐熱皿に並べる。","しょうゆ{g:soy}gとみりん{g:mirin}gと塩{g:salt}gをふる。","電子レンジで4分加熱し、取り出して2分蒸らす。","中まで火が通ったことを確かめる。","器に盛ってすぐに出す。"]'::jsonb),
    ('hakusai-fry', '白菜と{protein}の炒め', '中', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('grill', '{protein}のグリル', '洋', '主菜', '焼', 5, '["{protein}を一口大に切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて2分絡め、中まで火を通す。","火を止めて器に盛る。","塩{g:salt}gとこしょう{g:pepper}gを加えて味をととのえる。"]'::jsonb),
    ('tuna-onion-pasta', 'ツナと玉ねぎのパスタ', '洋', '丼麺', '炒', 9, '["スパゲティ{g:pasta}gを湯で6分ゆでる。","フライパンで{oil}{g:oil}gを熱し、{protein}と{veg}を2分炒める。","しょうゆ{g:soy}gとこしょう{g:pepper}gを加えて1分絡める。","ゆでたスパゲティを戻し入れて火を通し、器に盛る。"]'::jsonb),
    ('broccoli-grill', '{protein}とブロッコリーのグリル', '洋', '主菜', '焼', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。","塩{g:salt}gとこしょう{g:pepper}gを加えて味をととのえる。"]'::jsonb),
    ('salmon-tomato-pasta', '鮭とトマトのパスタ', '洋', '丼麺', '炒', 9, '["スパゲティ{g:pasta}gを湯で6分ゆでる。","フライパンで{oil}{g:oil}gを熱し、{protein}と{veg}を2分炒める。","しょうゆ{g:soy}gとこしょう{g:pepper}gを加えて1分絡める。","ゆでたスパゲティを戻し入れて火を通し、器に盛る。"]'::jsonb),
    ('tuna-sandwich', 'ツナの焼きサンド', '洋', '軽い品', '焼', 5, '["食パン{g:bread}gに{protein}をのせる。","フライパンを弱火にし、バター{g:butter}gで2分焼く。","塩{g:salt}gとこしょう{g:pepper}gを振る。","3分加熱して中まで温まったら皿に出す。"]'::jsonb),
    ('ethnic-tomato', '{protein}とトマトの炒め', 'エスニック', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","{veg}を加えて2分炒め、しょうゆ{g:soy}gとみりん{g:mirin}gを絡める。","火を止めて器に盛る。"]'::jsonb),
    ('tuna-ethnic', 'ツナとキャベツのエスニック炒め', 'エスニック', '主菜', '炒', 5, '["{protein}と{veg}を食べやすく切る。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分炒める。","{veg}と味噌{g:miso}gと砂糖{g:sugar}gと料理酒{g:sake}gを加えて2分炒め合わせる。","火を止めて器に盛る。"]'::jsonb),
    ('garlic-don', '{protein}のガーリック丼', 'エスニック', '丼麺', '焼', 5, '["{protein}を一口大に切る。{ginger}{g:ginger}gを添える。","フライパンを中火にし、{oil}{g:oil}gを熱して{protein}を3分焼く。","しょうゆ{g:soy}gとみりん{g:mirin}gを加えて2分絡め、中まで火を通す。","{rice}{g:rice}gを器に盛り、具をのせる。"]'::jsonb);

  insert into public.cook_recipe_options
    (recipe_id, slot_key, role, label, food_code, base_grams, sort_order, match_names, staple)
  values
    ('shoga', 'protein', 'protein', '鶏むね肉', '11220', 130, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('shoga', 'protein', 'protein', '鶏もも肉', '11224', 120, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('shoga', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('shoga', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('shoga', 'protein', 'protein', '厚揚げ', '04039', 80, 4, array['厚揚げ','あつあげ']::text[], false),
    ('shoga', 'ginger', 'other', 'しょうが', '06103', 20, 100, array['しょうが','生姜']::text[], false),
    ('shoga', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('shoga', 'soy', 'seasoning', 'しょうゆ', '17007', 12, 300, array['しょうゆ','醤油']::text[], true),
    ('shoga', 'mirin', 'seasoning', 'みりん', '16025', 12, 400, array['みりん','本みりん']::text[], true),
    ('shoga-don', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('shoga-don', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('shoga-don', 'protein', 'protein', '豚こま', '11115', 110, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('shoga-don', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('shoga-don', 'protein', 'protein', '厚揚げ', '04039', 70, 4, array['厚揚げ','あつあげ']::text[], false),
    ('shoga-don', 'ginger', 'other', 'しょうが', '06103', 20, 100, array['しょうが','生姜']::text[], false),
    ('shoga-don', 'rice', 'staple', 'ごはん', '01088', 180, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('shoga-don', 'oil', 'oil', 'サラダ油', '14006', 10, 300, array['サラダ油','油']::text[], true),
    ('shoga-don', 'soy', 'seasoning', 'しょうゆ', '17007', 12, 400, array['しょうゆ','醤油']::text[], true),
    ('shoga-don', 'mirin', 'seasoning', 'みりん', '16025', 12, 500, array['みりん','本みりん']::text[], true),
    ('shoga-light', 'protein', 'protein', '鶏むね肉', '11220', 170, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('shoga-light', 'protein', 'protein', '鶏もも肉', '11224', 150, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('shoga-light', 'protein', 'protein', '豚こま', '11115', 140, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('shoga-light', 'protein', 'protein', '牛こま', '11019', 130, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('shoga-light', 'ginger', 'other', 'しょうが', '06103', 20, 100, array['しょうが','生姜']::text[], false),
    ('shoga-light', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('shoga-light', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('shoga-light', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('shoga-light', 'salt', 'seasoning', '塩', '17012', 1, 500, array['塩','食塩']::text[], true),
    ('miso-itame', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('miso-itame', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('miso-itame', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('miso-itame', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('miso-itame', 'protein', 'protein', '厚揚げ', '04039', 80, 4, array['厚揚げ','あつあげ']::text[], false),
    ('miso-itame', 'veg', 'veg', 'キャベツ', '06061', 90, 100, array['キャベツ']::text[], false),
    ('miso-itame', 'veg', 'veg', '白菜', '06233', 110, 101, array['白菜','はくさい']::text[], false),
    ('miso-itame', 'veg', 'veg', 'ピーマン', '06245', 70, 102, array['ピーマン']::text[], false),
    ('miso-itame', 'veg', 'veg', 'もやし', '06291', 90, 103, array['もやし']::text[], false),
    ('miso-itame', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('miso-itame', 'miso', 'seasoning', '味噌', '17045', 12, 300, array['味噌','みそ']::text[], true),
    ('miso-itame', 'sugar', 'seasoning', '砂糖', '03003', 6, 400, array['砂糖']::text[], true),
    ('miso-itame', 'sake', 'seasoning', '料理酒', '17138', 8, 500, array['料理酒','酒']::text[], true),
    ('miso-don', 'protein', 'protein', '鶏むね肉', '11220', 110, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('miso-don', 'protein', 'protein', '鶏もも肉', '11224', 100, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('miso-don', 'protein', 'protein', '豚こま', '11115', 110, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('miso-don', 'protein', 'protein', '牛こま', '11019', 90, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('miso-don', 'protein', 'protein', '厚揚げ', '04039', 70, 4, array['厚揚げ','あつあげ']::text[], false),
    ('miso-don', 'veg', 'veg', 'キャベツ', '06061', 70, 100, array['キャベツ']::text[], false),
    ('miso-don', 'veg', 'veg', '白菜', '06233', 90, 101, array['白菜','はくさい']::text[], false),
    ('miso-don', 'veg', 'veg', 'ピーマン', '06245', 50, 102, array['ピーマン']::text[], false),
    ('miso-don', 'veg', 'veg', 'もやし', '06291', 70, 103, array['もやし']::text[], false),
    ('miso-don', 'rice', 'staple', 'ごはん', '01088', 170, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('miso-don', 'oil', 'oil', 'サラダ油', '14006', 8, 300, array['サラダ油','油']::text[], true),
    ('miso-don', 'miso', 'seasoning', '味噌', '17045', 12, 400, array['味噌','みそ']::text[], true),
    ('miso-don', 'sugar', 'seasoning', '砂糖', '03003', 6, 500, array['砂糖']::text[], true),
    ('miso-don', 'sake', 'seasoning', '料理酒', '17138', 8, 600, array['料理酒','酒']::text[], true),
    ('soy-itame', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('soy-itame', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('soy-itame', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('soy-itame', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('soy-itame', 'protein', 'protein', '厚揚げ', '04039', 80, 4, array['厚揚げ','あつあげ']::text[], false),
    ('soy-itame', 'veg', 'veg', 'キャベツ', '06061', 100, 100, array['キャベツ']::text[], false),
    ('soy-itame', 'veg', 'veg', '白菜', '06233', 120, 101, array['白菜','はくさい']::text[], false),
    ('soy-itame', 'veg', 'veg', 'ピーマン', '06245', 80, 102, array['ピーマン']::text[], false),
    ('soy-itame', 'veg', 'veg', 'もやし', '06291', 100, 103, array['もやし']::text[], false),
    ('soy-itame', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('soy-itame', 'soy', 'seasoning', 'しょうゆ', '17007', 12, 300, array['しょうゆ','醤油']::text[], true),
    ('soy-itame', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('soy-rice', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('soy-rice', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('soy-rice', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('soy-rice', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('soy-rice', 'protein', 'protein', '厚揚げ', '04039', 70, 4, array['厚揚げ','あつあげ']::text[], false),
    ('soy-rice', 'veg', 'veg', 'キャベツ', '06061', 80, 100, array['キャベツ']::text[], false),
    ('soy-rice', 'veg', 'veg', '白菜', '06233', 100, 101, array['白菜','はくさい']::text[], false),
    ('soy-rice', 'veg', 'veg', 'ピーマン', '06245', 60, 102, array['ピーマン']::text[], false),
    ('soy-rice', 'veg', 'veg', 'もやし', '06291', 80, 103, array['もやし']::text[], false),
    ('soy-rice', 'rice', 'staple', 'ごはん', '01088', 190, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('soy-rice', 'oil', 'oil', 'サラダ油', '14006', 10, 300, array['サラダ油','油']::text[], true),
    ('soy-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 400, array['しょうゆ','醤油']::text[], true),
    ('soy-rice', 'mirin', 'seasoning', 'みりん', '16025', 10, 500, array['みりん','本みりん']::text[], true),
    ('nikujaga', 'protein', 'protein', '鶏むね肉', '11220', 90, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('nikujaga', 'protein', 'protein', '鶏もも肉', '11224', 90, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('nikujaga', 'protein', 'protein', '豚こま', '11115', 100, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('nikujaga', 'protein', 'protein', '牛こま', '11019', 90, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('nikujaga', 'potato', 'veg', 'じゃがいも', '02017', 180, 100, array['じゃがいも','ジャガイモ','ポテト']::text[], false),
    ('nikujaga', 'onion', 'veg', '玉ねぎ', '06153', 70, 200, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('nikujaga', 'dashi', 'seasoning', '顆粒だし', '17028', 8, 300, array['顆粒だし','だし','和風だし']::text[], true),
    ('nikujaga', 'soy', 'seasoning', 'しょうゆ', '17007', 12, 400, array['しょうゆ','醤油']::text[], true),
    ('nikujaga', 'mirin', 'seasoning', 'みりん', '16025', 12, 500, array['みりん','本みりん']::text[], true),
    ('nikujaga', 'sugar', 'seasoning', '砂糖', '03003', 8, 600, array['砂糖']::text[], true),
    ('oyako', 'protein', 'protein', '鶏むね肉', '11220', 110, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('oyako', 'protein', 'protein', '鶏もも肉', '11224', 100, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('oyako', 'onion', 'veg', '玉ねぎ', '06153', 50, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('oyako', 'egg', 'egg', '卵', '12004', 50, 200, array['卵','たまご','玉子']::text[], false),
    ('oyako', 'rice', 'staple', 'ごはん', '01088', 180, 300, array['ごはん','ご飯','白米','お米']::text[], true),
    ('oyako', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 400, array['顆粒だし','だし','和風だし']::text[], true),
    ('oyako', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 500, array['しょうゆ','醤油']::text[], true),
    ('oyako', 'mirin', 'seasoning', 'みりん', '16025', 10, 600, array['みりん','本みりん']::text[], true),
    ('oyako-large', 'protein', 'protein', '鶏むね肉', '11220', 180, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('oyako-large', 'protein', 'protein', '鶏もも肉', '11224', 160, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('oyako-large', 'onion', 'veg', '玉ねぎ', '06153', 60, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('oyako-large', 'egg', 'egg', '卵', '12004', 100, 200, array['卵','たまご','玉子']::text[], false),
    ('oyako-large', 'rice', 'staple', 'ごはん', '01088', 260, 300, array['ごはん','ご飯','白米','お米']::text[], true),
    ('oyako-large', 'dashi', 'seasoning', '顆粒だし', '17028', 8, 400, array['顆粒だし','だし','和風だし']::text[], true),
    ('oyako-large', 'soy', 'seasoning', 'しょうゆ', '17007', 12, 500, array['しょうゆ','醤油']::text[], true),
    ('oyako-large', 'mirin', 'seasoning', 'みりん', '16025', 12, 600, array['みりん','本みりん']::text[], true),
    ('gyudon', 'protein', 'protein', '牛こま', '11019', 120, 0, array['牛こま','牛もも','牛肉']::text[], false),
    ('gyudon', 'rice', 'staple', 'ごはん', '01088', 200, 100, array['ごはん','ご飯','白米','お米']::text[], true),
    ('gyudon', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('gyudon', 'soy', 'seasoning', 'しょうゆ', '17007', 12, 300, array['しょうゆ','醤油']::text[], true),
    ('gyudon', 'mirin', 'seasoning', 'みりん', '16025', 12, 400, array['みりん','本みりん']::text[], true),
    ('gyudon', 'sugar', 'seasoning', '砂糖', '03003', 6, 500, array['砂糖']::text[], true),
    ('butadon', 'protein', 'protein', '豚こま', '11115', 120, 0, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('butadon', 'rice', 'staple', 'ごはん', '01088', 190, 100, array['ごはん','ご飯','白米','お米']::text[], true),
    ('butadon', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('butadon', 'soy', 'seasoning', 'しょうゆ', '17007', 12, 300, array['しょうゆ','醤油']::text[], true),
    ('butadon', 'mirin', 'seasoning', 'みりん', '16025', 10, 400, array['みりん','本みりん']::text[], true),
    ('butadon', 'sugar', 'seasoning', '砂糖', '03003', 4, 500, array['砂糖']::text[], true),
    ('chanchan', 'protein', 'protein', '鮭', '10134', 130, 0, array['鮭','さけ','サーモン','しろさけ']::text[], false),
    ('chanchan', 'veg', 'veg', 'キャベツ', '06061', 90, 100, array['キャベツ']::text[], false),
    ('chanchan', 'veg', 'veg', '玉ねぎ', '06153', 70, 101, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('chanchan', 'veg', 'veg', '白菜', '06233', 100, 102, array['白菜','はくさい']::text[], false),
    ('chanchan', 'miso', 'seasoning', '味噌', '17045', 12, 200, array['味噌','みそ']::text[], true),
    ('chanchan', 'sugar', 'seasoning', '砂糖', '03003', 6, 300, array['砂糖']::text[], true),
    ('chanchan', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 400, array['しょうゆ','醤油']::text[], true),
    ('salmon-fry', 'protein', 'protein', '鮭', '10134', 130, 0, array['鮭','さけ','サーモン','しろさけ']::text[], false),
    ('salmon-fry', 'veg', 'veg', 'キャベツ', '06061', 80, 100, array['キャベツ']::text[], false),
    ('salmon-fry', 'veg', 'veg', '白菜', '06233', 100, 101, array['白菜','はくさい']::text[], false),
    ('salmon-fry', 'veg', 'veg', 'ピーマン', '06245', 60, 102, array['ピーマン']::text[], false),
    ('salmon-fry', 'veg', 'veg', 'もやし', '06291', 80, 103, array['もやし']::text[], false),
    ('salmon-fry', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('salmon-fry', 'miso', 'seasoning', '味噌', '17045', 10, 300, array['味噌','みそ']::text[], true),
    ('salmon-fry', 'sugar', 'seasoning', '砂糖', '03003', 4, 400, array['砂糖']::text[], true),
    ('salmon-fry', 'sake', 'seasoning', '料理酒', '17138', 6, 500, array['料理酒','酒']::text[], true),
    ('salmon-rice', 'protein', 'protein', '鮭', '10134', 140, 0, array['鮭','さけ','サーモン','しろさけ']::text[], false),
    ('salmon-rice', 'rice', 'staple', 'ごはん', '01088', 170, 100, array['ごはん','ご飯','白米','お米']::text[], true),
    ('salmon-rice', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('salmon-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('salmon-rice', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('salmon-rice', 'sugar', 'seasoning', '砂糖', '03003', 4, 500, array['砂糖']::text[], true),
    ('nanban', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('nanban', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('nanban', 'onion', 'veg', '玉ねぎ', '06153', 60, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('nanban', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('nanban', 'vinegar', 'seasoning', '酢', '17015', 12, 300, array['酢','お酢']::text[], true),
    ('nanban', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 400, array['しょうゆ','醤油']::text[], true),
    ('nanban', 'sugar', 'seasoning', '砂糖', '03003', 8, 500, array['砂糖']::text[], true),
    ('steam-rice', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('steam-rice', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('steam-rice', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('steam-rice', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('steam-rice', 'rice', 'staple', 'ごはん', '01088', 180, 100, array['ごはん','ご飯','白米','お米']::text[], true),
    ('steam-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 200, array['しょうゆ','醤油']::text[], true),
    ('steam-rice', 'mirin', 'seasoning', 'みりん', '16025', 8, 300, array['みりん','本みりん']::text[], true),
    ('steam-rice', 'salt', 'seasoning', '塩', '17012', 1, 400, array['塩','食塩']::text[], true),
    ('steam-plate', 'protein', 'protein', '鶏むね肉', '11220', 170, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('steam-plate', 'protein', 'protein', '鶏もも肉', '11224', 150, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('steam-plate', 'protein', 'protein', '豚こま', '11115', 140, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('steam-plate', 'protein', 'protein', '牛こま', '11019', 120, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('steam-plate', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 100, array['しょうゆ','醤油']::text[], true),
    ('steam-plate', 'mirin', 'seasoning', 'みりん', '16025', 6, 200, array['みりん','本みりん']::text[], true),
    ('steam-plate', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('miso-soup-tofu', 'protein', 'protein', '木綿豆腐', '04032', 120, 0, array['木綿豆腐','豆腐']::text[], false),
    ('miso-soup-tofu', 'veg', 'veg', 'キャベツ', '06061', 40, 100, array['キャベツ']::text[], false),
    ('miso-soup-tofu', 'veg', 'veg', '白菜', '06233', 50, 101, array['白菜','はくさい']::text[], false),
    ('miso-soup-tofu', 'veg', 'veg', 'ピーマン', '06245', 40, 102, array['ピーマン']::text[], false),
    ('miso-soup-tofu', 'veg', 'veg', 'もやし', '06291', 40, 103, array['もやし']::text[], false),
    ('miso-soup-tofu', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 200, array['顆粒だし','だし','和風だし']::text[], true),
    ('miso-soup-tofu', 'miso', 'seasoning', '味噌', '17045', 12, 300, array['味噌','みそ']::text[], true),
    ('miso-soup-tofu', 'soy', 'seasoning', 'しょうゆ', '17007', 4, 400, array['しょうゆ','醤油']::text[], true),
    ('miso-soup-pork', 'protein', 'protein', '鶏むね肉', '11220', 70, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('miso-soup-pork', 'protein', 'protein', '鶏もも肉', '11224', 70, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('miso-soup-pork', 'protein', 'protein', '豚こま', '11115', 70, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('miso-soup-pork', 'protein', 'protein', '牛こま', '11019', 60, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('miso-soup-pork', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 100, array['顆粒だし','だし','和風だし']::text[], true),
    ('miso-soup-pork', 'miso', 'seasoning', '味噌', '17045', 12, 200, array['味噌','みそ']::text[], true),
    ('miso-soup-pork', 'soy', 'seasoning', 'しょうゆ', '17007', 4, 300, array['しょうゆ','醤油']::text[], true),
    ('hiyayakko', 'tofu', 'protein', '絹ごし豆腐', '04033', 150, 0, array['絹ごし豆腐','絹豆腐','冷奴']::text[], false),
    ('hiyayakko', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 100, array['しょうゆ','醤油']::text[], true),
    ('hiyayakko', 'ginger', 'other', 'しょうが', '06103', 20, 200, array['しょうが','生姜']::text[], false),
    ('ohitashi-leaf', 'veg', 'veg', 'キャベツ', '06061', 80, 0, array['キャベツ']::text[], false),
    ('ohitashi-leaf', 'veg', 'veg', '白菜', '06233', 90, 1, array['白菜','はくさい']::text[], false),
    ('ohitashi-leaf', 'veg', 'veg', 'ほうれん草', '06267', 70, 2, array['ほうれん草','ほうれんそう']::text[], false),
    ('ohitashi-leaf', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 100, array['しょうゆ','醤油']::text[], true),
    ('ohitashi-leaf', 'dashi', 'seasoning', '顆粒だし', '17028', 3, 200, array['顆粒だし','だし','和風だし']::text[], true),
    ('cabbage-ae', 'veg', 'veg', 'キャベツ', '06061', 80, 0, array['キャベツ']::text[], false),
    ('cabbage-ae', 'veg', 'veg', '白菜', '06233', 90, 1, array['白菜','はくさい']::text[], false),
    ('cabbage-ae', 'veg', 'veg', 'ピーマン', '06245', 60, 2, array['ピーマン']::text[], false),
    ('cabbage-ae', 'veg', 'veg', 'もやし', '06291', 80, 3, array['もやし']::text[], false),
    ('cabbage-ae', 'salt', 'seasoning', '塩', '17012', 1, 100, array['塩','食塩']::text[], true),
    ('cabbage-ae', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 200, array['しょうゆ','醤油']::text[], true),
    ('cabbage-ae', 'vinegar', 'seasoning', '酢', '17015', 8, 300, array['酢','お酢']::text[], true),
    ('cabbage-ae', 'sugar', 'seasoning', '砂糖', '03003', 4, 400, array['砂糖']::text[], true),
    ('cucumber-ae', 'veg', 'veg', 'きゅうり', '06065', 80, 0, array['きゅうり']::text[], false),
    ('cucumber-ae', 'salt', 'seasoning', '塩', '17012', 1, 100, array['塩','食塩']::text[], true),
    ('cucumber-ae', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 200, array['しょうゆ','醤油']::text[], true),
    ('cucumber-ae', 'vinegar', 'seasoning', '酢', '17015', 8, 300, array['酢','お酢']::text[], true),
    ('cucumber-ae', 'sugar', 'seasoning', '砂糖', '03003', 4, 400, array['砂糖']::text[], true),
    ('potato-butter', 'veg', 'veg', 'じゃがいも', '02017', 160, 0, array['じゃがいも','ジャガイモ','ポテト']::text[], false),
    ('potato-butter', 'veg', 'veg', 'かぼちゃ', '06049', 120, 1, array['かぼちゃ']::text[], false),
    ('potato-butter', 'butter', 'oil', 'バター', '14017', 6, 100, array['バター']::text[], true),
    ('potato-butter', 'salt', 'seasoning', '塩', '17012', 1, 200, array['塩','食塩']::text[], true),
    ('potato-butter', 'pepper', 'seasoning', 'こしょう', '17063', 1, 300, array['こしょう','胡椒','コショウ']::text[], true),
    ('tamago', 'egg', 'egg', '卵', '12004', 100, 0, array['卵','たまご','玉子']::text[], false),
    ('tamago', 'oil', 'oil', 'サラダ油', '14006', 1, 100, array['サラダ油','油']::text[], true),
    ('tamago', 'salt', 'seasoning', '塩', '17012', 1, 200, array['塩','食塩']::text[], true),
    ('tamago', 'pepper', 'seasoning', 'こしょう', '17063', 1, 300, array['こしょう','胡椒','コショウ']::text[], true),
    ('tamago-veg', 'egg', 'egg', '卵', '12004', 100, 0, array['卵','たまご','玉子']::text[], false),
    ('tamago-veg', 'veg', 'veg', 'キャベツ', '06061', 70, 100, array['キャベツ']::text[], false),
    ('tamago-veg', 'veg', 'veg', '白菜', '06233', 80, 101, array['白菜','はくさい']::text[], false),
    ('tamago-veg', 'veg', 'veg', 'ピーマン', '06245', 50, 102, array['ピーマン']::text[], false),
    ('tamago-veg', 'veg', 'veg', 'もやし', '06291', 70, 103, array['もやし']::text[], false),
    ('tamago-veg', 'oil', 'oil', 'サラダ油', '14006', 4, 200, array['サラダ油','油']::text[], true),
    ('tamago-veg', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('tamago-veg', 'pepper', 'seasoning', 'こしょう', '17063', 1, 400, array['こしょう','胡椒','コショウ']::text[], true),
    ('tamago-gohan', 'egg', 'egg', '卵', '12004', 50, 0, array['卵','たまご','玉子']::text[], false),
    ('tamago-gohan', 'rice', 'staple', 'ごはん', '01088', 160, 100, array['ごはん','ご飯','白米','お米']::text[], true),
    ('tamago-gohan', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 200, array['しょうゆ','醤油']::text[], true),
    ('tamago-gohan', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('natto-gohan', 'protein', 'protein', '納豆', '04046', 50, 0, array['納豆']::text[], false),
    ('natto-gohan', 'rice', 'staple', 'ごはん', '01088', 160, 100, array['ごはん','ご飯','白米','お米']::text[], true),
    ('natto-gohan', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 200, array['しょうゆ','醤油']::text[], true),
    ('natto-gohan', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('udon', 'protein', 'protein', '鶏むね肉', '11220', 80, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('udon', 'protein', 'protein', '鶏もも肉', '11224', 80, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('udon', 'protein', 'protein', '豚こま', '11115', 80, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('udon', 'protein', 'protein', '牛こま', '11019', 70, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('udon', 'veg', 'veg', '玉ねぎ', '06153', 40, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('udon', 'veg', 'veg', 'ねぎ', '06226', 40, 101, array['ねぎ','長ねぎ','ネギ']::text[], false),
    ('udon', 'rice', 'staple', 'うどん', '01039', 200, 200, array['うどん']::text[], false),
    ('udon', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 300, array['顆粒だし','だし','和風だし']::text[], true),
    ('udon', 'miso', 'seasoning', '味噌', '17045', 8, 400, array['味噌','みそ']::text[], true),
    ('udon', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 500, array['しょうゆ','醤油']::text[], true),
    ('soba', 'protein', 'protein', '鶏むね肉', '11220', 70, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('soba', 'protein', 'protein', '鶏もも肉', '11224', 70, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('soba', 'protein', 'protein', '豚こま', '11115', 70, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('soba', 'protein', 'protein', '牛こま', '11019', 60, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('soba', 'veg', 'veg', 'ねぎ', '06226', 40, 100, array['ねぎ','長ねぎ','ネギ']::text[], false),
    ('soba', 'rice', 'staple', 'そば', '01128', 180, 200, array['そば','蕎麦']::text[], false),
    ('soba', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 300, array['顆粒だし','だし','和風だし']::text[], true),
    ('soba', 'miso', 'seasoning', '味噌', '17045', 8, 400, array['味噌','みそ']::text[], true),
    ('soba', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 500, array['しょうゆ','醤油']::text[], true),
    ('chahan', 'protein', 'protein', '鶏むね肉', '11220', 80, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chahan', 'protein', 'protein', '鶏もも肉', '11224', 80, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('chahan', 'protein', 'protein', '豚こま', '11115', 90, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('chahan', 'protein', 'protein', '牛こま', '11019', 70, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('chahan', 'egg', 'egg', '卵', '12004', 50, 100, array['卵','たまご','玉子']::text[], false),
    ('chahan', 'rice', 'staple', 'ごはん', '01088', 200, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('chahan', 'oil', 'oil', 'サラダ油', '14006', 8, 300, array['サラダ油','油']::text[], true),
    ('chahan', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('chahan', 'salt', 'seasoning', '塩', '17012', 1, 500, array['塩','食塩']::text[], true),
    ('chahan-veg', 'protein', 'protein', '鶏むね肉', '11220', 70, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chahan-veg', 'protein', 'protein', '鶏もも肉', '11224', 70, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('chahan-veg', 'protein', 'protein', '豚こま', '11115', 80, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('chahan-veg', 'protein', 'protein', '牛こま', '11019', 60, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('chahan-veg', 'veg', 'veg', 'キャベツ', '06061', 50, 100, array['キャベツ']::text[], false),
    ('chahan-veg', 'veg', 'veg', '白菜', '06233', 60, 101, array['白菜','はくさい']::text[], false),
    ('chahan-veg', 'veg', 'veg', 'ピーマン', '06245', 40, 102, array['ピーマン']::text[], false),
    ('chahan-veg', 'veg', 'veg', 'もやし', '06291', 50, 103, array['もやし']::text[], false),
    ('chahan-veg', 'egg', 'egg', '卵', '12004', 50, 200, array['卵','たまご','玉子']::text[], false),
    ('chahan-veg', 'rice', 'staple', 'ごはん', '01088', 190, 300, array['ごはん','ご飯','白米','お米']::text[], true),
    ('chahan-veg', 'oil', 'oil', 'サラダ油', '14006', 8, 400, array['サラダ油','油']::text[], true),
    ('chahan-veg', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 500, array['しょうゆ','醤油']::text[], true),
    ('chahan-veg', 'salt', 'seasoning', '塩', '17012', 1, 600, array['塩','食塩']::text[], true),
    ('mapo', 'protein', 'protein', '鶏むね肉', '11220', 80, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('mapo', 'protein', 'protein', '鶏もも肉', '11224', 70, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('mapo', 'protein', 'protein', '豚こま', '11115', 90, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('mapo', 'protein', 'protein', '牛こま', '11019', 70, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('mapo', 'tofu', 'protein', '木綿豆腐', '04032', 180, 100, array['木綿豆腐','豆腐']::text[], false),
    ('mapo', 'negi', 'veg', 'ねぎ', '06226', 40, 200, array['ねぎ','長ねぎ','ネギ']::text[], false),
    ('mapo', 'oil', 'oil', 'ごま油', '14002', 6, 300, array['ごま油']::text[], true),
    ('mapo', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('mapo', 'miso', 'seasoning', '味噌', '17045', 10, 500, array['味噌','みそ']::text[], true),
    ('mapo', 'sugar', 'seasoning', '砂糖', '03003', 4, 600, array['砂糖']::text[], true),
    ('mapo-don', 'protein', 'protein', '豚こま', '11115', 80, 0, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('mapo-don', 'protein', 'protein', '鶏むね肉', '11220', 90, 1, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('mapo-don', 'tofu', 'protein', '木綿豆腐', '04032', 150, 100, array['木綿豆腐','豆腐']::text[], false),
    ('mapo-don', 'negi', 'veg', 'ねぎ', '06226', 40, 200, array['ねぎ','長ねぎ','ネギ']::text[], false),
    ('mapo-don', 'rice', 'staple', 'ごはん', '01088', 180, 300, array['ごはん','ご飯','白米','お米']::text[], true),
    ('mapo-don', 'oil', 'oil', 'ごま油', '14002', 6, 400, array['ごま油']::text[], true),
    ('mapo-don', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 500, array['しょうゆ','醤油']::text[], true),
    ('mapo-don', 'miso', 'seasoning', '味噌', '17045', 10, 600, array['味噌','みそ']::text[], true),
    ('mapo-don', 'sugar', 'seasoning', '砂糖', '03003', 4, 700, array['砂糖']::text[], true),
    ('hoikoro', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('hoikoro', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('hoikoro', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('hoikoro', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('hoikoro', 'veg', 'veg', 'ピーマン', '06245', 70, 100, array['ピーマン']::text[], false),
    ('hoikoro', 'veg', 'veg', 'キャベツ', '06061', 80, 101, array['キャベツ']::text[], false),
    ('hoikoro', 'veg', 'veg', 'もやし', '06291', 80, 102, array['もやし']::text[], false),
    ('hoikoro', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('hoikoro', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 300, array['しょうゆ','醤油']::text[], true),
    ('hoikoro', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('subuta', 'protein', 'protein', '豚こま', '11115', 130, 0, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('subuta', 'onion', 'veg', '玉ねぎ', '06153', 70, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('subuta', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('subuta', 'vinegar', 'seasoning', '酢', '17015', 14, 300, array['酢','お酢']::text[], true),
    ('subuta', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 400, array['しょうゆ','醤油']::text[], true),
    ('subuta', 'sugar', 'seasoning', '砂糖', '03003', 10, 500, array['砂糖']::text[], true),
    ('tomato-egg', 'egg', 'egg', '卵', '12004', 100, 0, array['卵','たまご','玉子']::text[], false),
    ('tomato-egg', 'veg', 'veg', 'トマト', '06182', 100, 100, array['トマト']::text[], false),
    ('tomato-egg', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('tomato-egg', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('tomato-egg', 'pepper', 'seasoning', 'こしょう', '17063', 1, 400, array['こしょう','胡椒','コショウ']::text[], true),
    ('tomato-egg-rice', 'egg', 'egg', '卵', '12004', 100, 0, array['卵','たまご','玉子']::text[], false),
    ('tomato-egg-rice', 'veg', 'veg', 'トマト', '06182', 80, 100, array['トマト']::text[], false),
    ('tomato-egg-rice', 'rice', 'staple', 'ごはん', '01088', 160, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('tomato-egg-rice', 'oil', 'oil', 'サラダ油', '14006', 6, 300, array['サラダ油','油']::text[], true),
    ('tomato-egg-rice', 'salt', 'seasoning', '塩', '17012', 1, 400, array['塩','食塩']::text[], true),
    ('tomato-egg-rice', 'pepper', 'seasoning', 'こしょう', '17063', 1, 500, array['こしょう','胡椒','コショウ']::text[], true),
    ('chinjao', 'protein', 'protein', '鶏むね肉', '11220', 130, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chinjao', 'protein', 'protein', '鶏もも肉', '11224', 120, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('chinjao', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('chinjao', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('chinjao', 'veg', 'veg', 'ピーマン', '06245', 80, 100, array['ピーマン']::text[], false),
    ('chinjao', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('chinjao', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 300, array['しょうゆ','醤油']::text[], true),
    ('chinjao', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('moyashi-pork', 'protein', 'protein', '豚こま', '11115', 120, 0, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('moyashi-pork', 'protein', 'protein', '鶏むね肉', '11220', 130, 1, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('moyashi-pork', 'protein', 'protein', '牛こま', '11019', 100, 2, array['牛こま','牛もも','牛肉']::text[], false),
    ('moyashi-pork', 'veg', 'veg', 'もやし', '06291', 100, 100, array['もやし']::text[], false),
    ('moyashi-pork', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('moyashi-pork', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 300, array['しょうゆ','醤油']::text[], true),
    ('moyashi-pork', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('hakusai-pork', 'protein', 'protein', '鶏むね肉', '11220', 100, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('hakusai-pork', 'protein', 'protein', '鶏もも肉', '11224', 100, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('hakusai-pork', 'protein', 'protein', '豚こま', '11115', 110, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('hakusai-pork', 'protein', 'protein', '牛こま', '11019', 90, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('hakusai-pork', 'veg', 'veg', '白菜', '06233', 120, 100, array['白菜','はくさい']::text[], false),
    ('hakusai-pork', 'dashi', 'seasoning', '顆粒だし', '17028', 8, 200, array['顆粒だし','だし','和風だし']::text[], true),
    ('hakusai-pork', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 300, array['しょうゆ','醤油']::text[], true),
    ('hakusai-pork', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('hakusai-pork', 'sugar', 'seasoning', '砂糖', '03003', 4, 500, array['砂糖']::text[], true),
    ('tofu-stir', 'protein', 'protein', '木綿豆腐', '04032', 200, 0, array['木綿豆腐','豆腐']::text[], false),
    ('tofu-stir', 'veg', 'veg', 'キャベツ', '06061', 70, 100, array['キャベツ']::text[], false),
    ('tofu-stir', 'veg', 'veg', '白菜', '06233', 80, 101, array['白菜','はくさい']::text[], false),
    ('tofu-stir', 'veg', 'veg', 'ピーマン', '06245', 50, 102, array['ピーマン']::text[], false),
    ('tofu-stir', 'veg', 'veg', 'もやし', '06291', 70, 103, array['もやし']::text[], false),
    ('tofu-stir', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('tofu-stir', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('tofu-stir', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('garlic-chicken', 'protein', 'protein', '鶏むね肉', '11220', 150, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('garlic-chicken', 'protein', 'protein', '鶏もも肉', '11224', 140, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('garlic-chicken', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('garlic-chicken', 'protein', 'protein', '牛こま', '11019', 120, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('garlic-chicken', 'ginger', 'other', 'にんにく', '06223', 20, 100, array['にんにく','ニンニク']::text[], false),
    ('garlic-chicken', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('garlic-chicken', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 300, array['しょうゆ','醤油']::text[], true),
    ('garlic-chicken', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('egg-drop', 'protein', 'egg', '卵', '12004', 50, 0, array['卵','たまご','玉子']::text[], false),
    ('egg-drop', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 100, array['顆粒だし','だし','和風だし']::text[], true),
    ('egg-drop', 'miso', 'seasoning', '味噌', '17045', 6, 200, array['味噌','みそ']::text[], true),
    ('egg-drop', 'soy', 'seasoning', 'しょうゆ', '17007', 4, 300, array['しょうゆ','醤油']::text[], true),
    ('tuna-cabbage', 'protein', 'protein', 'ツナ', '10263', 70, 0, array['ツナ','ツナ缶']::text[], false),
    ('tuna-cabbage', 'veg', 'veg', 'キャベツ', '06061', 70, 100, array['キャベツ']::text[], false),
    ('tuna-cabbage', 'pasta', 'staple', 'スパゲティ', '01064', 180, 200, array['スパゲティ','パスタ']::text[], false),
    ('tuna-cabbage', 'oil', 'oil', 'サラダ油', '14006', 6, 300, array['サラダ油','油']::text[], true),
    ('tuna-cabbage', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('tuna-cabbage', 'pepper', 'seasoning', 'こしょう', '17063', 1, 500, array['こしょう','胡椒','コショウ']::text[], true),
    ('tuna-tomato', 'protein', 'protein', 'ツナ', '10263', 70, 0, array['ツナ','ツナ缶']::text[], false),
    ('tuna-tomato', 'veg', 'veg', 'トマト', '06182', 80, 100, array['トマト']::text[], false),
    ('tuna-tomato', 'pasta', 'staple', 'スパゲティ', '01064', 180, 200, array['スパゲティ','パスタ']::text[], false),
    ('tuna-tomato', 'oil', 'oil', 'サラダ油', '14006', 6, 300, array['サラダ油','油']::text[], true),
    ('tuna-tomato', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 400, array['しょうゆ','醤油']::text[], true),
    ('tuna-tomato', 'pepper', 'seasoning', 'こしょう', '17063', 1, 500, array['こしょう','胡椒','コショウ']::text[], true),
    ('salmon-pasta', 'protein', 'protein', '鮭', '10134', 100, 0, array['鮭','さけ','サーモン','しろさけ']::text[], false),
    ('salmon-pasta', 'veg', 'veg', 'ほうれん草', '06267', 50, 100, array['ほうれん草','ほうれんそう']::text[], false),
    ('salmon-pasta', 'pasta', 'staple', 'スパゲティ', '01064', 170, 200, array['スパゲティ','パスタ']::text[], false),
    ('salmon-pasta', 'oil', 'oil', 'サラダ油', '14006', 6, 300, array['サラダ油','油']::text[], true),
    ('salmon-pasta', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 400, array['しょうゆ','醤油']::text[], true),
    ('salmon-pasta', 'pepper', 'seasoning', 'こしょう', '17063', 1, 500, array['こしょう','胡椒','コショウ']::text[], true),
    ('chicken-tomato', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chicken-tomato', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('chicken-tomato', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('chicken-tomato', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('chicken-tomato', 'veg', 'veg', 'トマト', '06182', 100, 100, array['トマト']::text[], false),
    ('chicken-tomato', 'dashi', 'seasoning', '顆粒だし', '17028', 4, 200, array['顆粒だし','だし','和風だし']::text[], true),
    ('chicken-tomato', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 300, array['しょうゆ','醤油']::text[], true),
    ('chicken-tomato', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('chicken-tomato', 'sugar', 'seasoning', '砂糖', '03003', 4, 500, array['砂糖']::text[], true),
    ('chicken-tomato-rice', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chicken-tomato-rice', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('chicken-tomato-rice', 'protein', 'protein', '豚こま', '11115', 110, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('chicken-tomato-rice', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('chicken-tomato-rice', 'veg', 'veg', 'トマト', '06182', 80, 100, array['トマト']::text[], false),
    ('chicken-tomato-rice', 'rice', 'staple', 'ごはん', '01088', 170, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('chicken-tomato-rice', 'dashi', 'seasoning', '顆粒だし', '17028', 4, 300, array['顆粒だし','だし','和風だし']::text[], true),
    ('chicken-tomato-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 400, array['しょうゆ','醤油']::text[], true),
    ('chicken-tomato-rice', 'mirin', 'seasoning', 'みりん', '16025', 6, 500, array['みりん','本みりん']::text[], true),
    ('chicken-tomato-rice', 'sugar', 'seasoning', '砂糖', '03003', 4, 600, array['砂糖']::text[], true),
    ('omelette', 'egg', 'egg', '卵', '12004', 100, 0, array['卵','たまご','玉子']::text[], false),
    ('omelette', 'oil', 'oil', 'サラダ油', '14006', 4, 100, array['サラダ油','油']::text[], true),
    ('omelette', 'salt', 'seasoning', '塩', '17012', 1, 200, array['塩','食塩']::text[], true),
    ('omelette', 'pepper', 'seasoning', 'こしょう', '17063', 1, 300, array['こしょう','胡椒','コショウ']::text[], true),
    ('omelette-veg', 'veg', 'veg', 'トマト', '06182', 60, 0, array['トマト']::text[], false),
    ('omelette-veg', 'veg', 'veg', 'ほうれん草', '06267', 40, 1, array['ほうれん草','ほうれんそう']::text[], false),
    ('omelette-veg', 'veg', 'veg', '玉ねぎ', '06153', 50, 2, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('omelette-veg', 'egg', 'egg', '卵', '12004', 100, 100, array['卵','たまご','玉子']::text[], false),
    ('omelette-veg', 'oil', 'oil', 'サラダ油', '14006', 4, 200, array['サラダ油','油']::text[], true),
    ('omelette-veg', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('omelette-veg', 'pepper', 'seasoning', 'こしょう', '17063', 1, 400, array['こしょう','胡椒','コショウ']::text[], true),
    ('hamburger', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('hamburger', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('hamburger', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('hamburger', 'protein', 'protein', '牛こま', '11019', 120, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('hamburger', 'onion', 'veg', '玉ねぎ', '06153', 50, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('hamburger', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('hamburger', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('hamburger', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('saute', 'protein', 'protein', '鶏むね肉', '11220', 150, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('saute', 'protein', 'protein', '鶏もも肉', '11224', 140, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('saute', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('saute', 'protein', 'protein', '牛こま', '11019', 120, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('saute', 'oil', 'oil', 'サラダ油', '14006', 8, 100, array['サラダ油','油']::text[], true),
    ('saute', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 200, array['しょうゆ','醤油']::text[], true),
    ('saute', 'mirin', 'seasoning', 'みりん', '16025', 6, 300, array['みりん','本みりん']::text[], true),
    ('saute', 'salt', 'seasoning', '塩', '17012', 1, 400, array['塩','食塩']::text[], true),
    ('saute-veg', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('saute-veg', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('saute-veg', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('saute-veg', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('saute-veg', 'veg', 'veg', 'ブロッコリー', '06264', 80, 100, array['ブロッコリー']::text[], false),
    ('saute-veg', 'veg', 'veg', 'ピーマン', '06245', 60, 101, array['ピーマン']::text[], false),
    ('saute-veg', 'veg', 'veg', 'ほうれん草', '06267', 60, 102, array['ほうれん草','ほうれんそう']::text[], false),
    ('saute-veg', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('saute-veg', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 300, array['しょうゆ','醤油']::text[], true),
    ('saute-veg', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('gratin-toast', 'protein', 'protein', 'ツナ', '10263', 60, 0, array['ツナ','ツナ缶']::text[], false),
    ('gratin-toast', 'bread', 'staple', '食パン', '01026', 70, 100, array['食パン','パン']::text[], false),
    ('gratin-toast', 'butter', 'oil', 'バター', '14017', 5, 200, array['バター']::text[], true),
    ('gratin-toast', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('gratin-toast', 'pepper', 'seasoning', 'こしょう', '17063', 1, 400, array['こしょう','胡椒','コショウ']::text[], true),
    ('cheese-toast', 'protein', 'other', 'プロセスチーズ', '13040', 20, 0, array['チーズ','プロセスチーズ']::text[], false),
    ('cheese-toast', 'bread', 'staple', '食パン', '01026', 70, 100, array['食パン','パン']::text[], false),
    ('cheese-toast', 'butter', 'oil', 'バター', '14017', 5, 200, array['バター']::text[], true),
    ('cheese-toast', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('cheese-toast', 'pepper', 'seasoning', 'こしょう', '17063', 1, 400, array['こしょう','胡椒','コショウ']::text[], true),
    ('egg-bread', 'protein', 'egg', '卵', '12004', 50, 0, array['卵','たまご','玉子']::text[], false),
    ('egg-bread', 'bread', 'staple', '食パン', '01026', 70, 100, array['食パン','パン']::text[], false),
    ('egg-bread', 'butter', 'oil', 'バター', '14017', 5, 200, array['バター']::text[], true),
    ('egg-bread', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('egg-bread', 'pepper', 'seasoning', 'こしょう', '17063', 1, 400, array['こしょう','胡椒','コショウ']::text[], true),
    ('potato-salad', 'veg', 'veg', 'じゃがいも', '02017', 120, 0, array['じゃがいも','ジャガイモ','ポテト']::text[], false),
    ('potato-salad', 'salt', 'seasoning', '塩', '17012', 1, 100, array['塩','食塩']::text[], true),
    ('potato-salad', 'soy', 'seasoning', 'しょうゆ', '17007', 4, 200, array['しょうゆ','醤油']::text[], true),
    ('potato-salad', 'vinegar', 'seasoning', '酢', '17015', 6, 300, array['酢','お酢']::text[], true),
    ('potato-salad', 'sugar', 'seasoning', '砂糖', '03003', 3, 400, array['砂糖']::text[], true),
    ('broccoli-ae', 'veg', 'veg', 'ブロッコリー', '06264', 80, 0, array['ブロッコリー']::text[], false),
    ('broccoli-ae', 'salt', 'seasoning', '塩', '17012', 1, 100, array['塩','食塩']::text[], true),
    ('broccoli-ae', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 200, array['しょうゆ','醤油']::text[], true),
    ('broccoli-ae', 'vinegar', 'seasoning', '酢', '17015', 6, 300, array['酢','お酢']::text[], true),
    ('broccoli-ae', 'sugar', 'seasoning', '砂糖', '03003', 3, 400, array['砂糖']::text[], true),
    ('minestrone', 'protein', 'protein', '木綿豆腐', '04032', 80, 0, array['木綿豆腐','豆腐']::text[], false),
    ('minestrone', 'protein', 'protein', '鶏むね肉', '11220', 70, 1, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('minestrone', 'veg', 'veg', 'トマト', '06182', 80, 100, array['トマト']::text[], false),
    ('minestrone', 'dashi', 'seasoning', '顆粒だし', '17028', 4, 200, array['顆粒だし','だし','和風だし']::text[], true),
    ('minestrone', 'miso', 'seasoning', '味噌', '17045', 6, 300, array['味噌','みそ']::text[], true),
    ('minestrone', 'soy', 'seasoning', 'しょうゆ', '17007', 4, 400, array['しょうゆ','醤油']::text[], true),
    ('creamless-stew', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('creamless-stew', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('creamless-stew', 'protein', 'protein', '豚こま', '11115', 110, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('creamless-stew', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('creamless-stew', 'potato', 'veg', 'じゃがいも', '02017', 150, 100, array['じゃがいも','ジャガイモ','ポテト']::text[], false),
    ('creamless-stew', 'onion', 'veg', '玉ねぎ', '06153', 60, 200, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('creamless-stew', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 300, array['顆粒だし','だし','和風だし']::text[], true),
    ('creamless-stew', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('creamless-stew', 'mirin', 'seasoning', 'みりん', '16025', 8, 500, array['みりん','本みりん']::text[], true),
    ('creamless-stew', 'sugar', 'seasoning', '砂糖', '03003', 4, 600, array['砂糖']::text[], true),
    ('fish-meuniere', 'protein', 'protein', '鮭', '10134', 140, 0, array['鮭','さけ','サーモン','しろさけ']::text[], false),
    ('fish-meuniere', 'oil', 'oil', 'バター', '14017', 6, 100, array['バター']::text[], true),
    ('fish-meuniere', 'soy', 'seasoning', 'しょうゆ', '17007', 4, 200, array['しょうゆ','醤油']::text[], true),
    ('fish-meuniere', 'mirin', 'seasoning', 'みりん', '16025', 4, 300, array['みりん','本みりん']::text[], true),
    ('fish-meuniere', 'salt', 'seasoning', '塩', '17012', 1, 400, array['塩','食塩']::text[], true),
    ('garlic-tomato', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('garlic-tomato', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('garlic-tomato', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('garlic-tomato', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('garlic-tomato', 'veg', 'veg', 'トマト', '06182', 90, 100, array['トマト']::text[], false),
    ('garlic-tomato', 'ginger', 'other', 'にんにく', '06223', 20, 200, array['にんにく','ニンニク']::text[], false),
    ('garlic-tomato', 'oil', 'oil', 'サラダ油', '14006', 8, 300, array['サラダ油','油']::text[], true),
    ('garlic-tomato', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('garlic-tomato', 'mirin', 'seasoning', 'みりん', '16025', 6, 500, array['みりん','本みりん']::text[], true),
    ('garlic-cabbage', 'protein', 'protein', '鶏むね肉', '11220', 130, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('garlic-cabbage', 'protein', 'protein', '鶏もも肉', '11224', 120, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('garlic-cabbage', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('garlic-cabbage', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('garlic-cabbage', 'veg', 'veg', 'キャベツ', '06061', 90, 100, array['キャベツ']::text[], false),
    ('garlic-cabbage', 'ginger', 'other', 'にんにく', '06223', 20, 200, array['にんにく','ニンニク']::text[], false),
    ('garlic-cabbage', 'oil', 'oil', 'サラダ油', '14006', 8, 300, array['サラダ油','油']::text[], true),
    ('garlic-cabbage', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('garlic-cabbage', 'mirin', 'seasoning', 'みりん', '16025', 6, 500, array['みりん','本みりん']::text[], true),
    ('ethnic-veg', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('ethnic-veg', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('ethnic-veg', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('ethnic-veg', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('ethnic-veg', 'veg', 'veg', 'キャベツ', '06061', 80, 100, array['キャベツ']::text[], false),
    ('ethnic-veg', 'veg', 'veg', '白菜', '06233', 90, 101, array['白菜','はくさい']::text[], false),
    ('ethnic-veg', 'veg', 'veg', 'ピーマン', '06245', 70, 102, array['ピーマン']::text[], false),
    ('ethnic-veg', 'veg', 'veg', 'もやし', '06291', 80, 103, array['もやし']::text[], false),
    ('ethnic-veg', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('ethnic-veg', 'miso', 'seasoning', '味噌', '17045', 8, 300, array['味噌','みそ']::text[], true),
    ('ethnic-veg', 'sugar', 'seasoning', '砂糖', '03003', 4, 400, array['砂糖']::text[], true),
    ('ethnic-veg', 'sake', 'seasoning', '料理酒', '17138', 6, 500, array['料理酒','酒']::text[], true),
    ('ethnic-soup', 'protein', 'protein', '鶏むね肉', '11220', 80, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('ethnic-soup', 'protein', 'protein', '鶏もも肉', '11224', 80, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('ethnic-soup', 'protein', 'protein', '豚こま', '11115', 80, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('ethnic-soup', 'protein', 'protein', '牛こま', '11019', 70, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('ethnic-soup', 'veg', 'veg', 'トマト', '06182', 80, 100, array['トマト']::text[], false),
    ('ethnic-soup', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 200, array['顆粒だし','だし','和風だし']::text[], true),
    ('ethnic-soup', 'miso', 'seasoning', '味噌', '17045', 8, 300, array['味噌','みそ']::text[], true),
    ('ethnic-soup', 'soy', 'seasoning', 'しょうゆ', '17007', 4, 400, array['しょうゆ','醤油']::text[], true),
    ('ethnic-don', 'protein', 'protein', '鶏むね肉', '11220', 130, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('ethnic-don', 'protein', 'protein', '鶏もも肉', '11224', 120, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('ethnic-don', 'protein', 'protein', '豚こま', '11115', 110, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('ethnic-don', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('ethnic-don', 'veg', 'veg', 'トマト', '06182', 70, 100, array['トマト']::text[], false),
    ('ethnic-don', 'rice', 'staple', 'ごはん', '01088', 180, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('ethnic-don', 'dashi', 'seasoning', '顆粒だし', '17028', 4, 300, array['顆粒だし','だし','和風だし']::text[], true),
    ('ethnic-don', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('ethnic-don', 'mirin', 'seasoning', 'みりん', '16025', 6, 500, array['みりん','本みりん']::text[], true),
    ('ethnic-don', 'sugar', 'seasoning', '砂糖', '03003', 4, 600, array['砂糖']::text[], true),
    ('chicken-broccoli', 'protein', 'protein', '鶏むね肉', '11220', 170, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chicken-broccoli', 'veg', 'veg', 'ブロッコリー', '06264', 100, 100, array['ブロッコリー']::text[], false),
    ('chicken-broccoli', 'oil', 'oil', 'サラダ油', '14006', 10, 200, array['サラダ油','油']::text[], true),
    ('chicken-broccoli', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 300, array['しょうゆ','醤油']::text[], true),
    ('chicken-broccoli', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('chicken-broccoli', 'sugar', 'seasoning', '砂糖', '03003', 12, 500, array['砂糖']::text[], true),
    ('chicken-broccoli-any', 'protein', 'protein', '鶏むね肉', '11220', 150, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chicken-broccoli-any', 'protein', 'protein', '鶏もも肉', '11224', 140, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('chicken-broccoli-any', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('chicken-broccoli-any', 'protein', 'protein', '牛こま', '11019', 120, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('chicken-broccoli-any', 'veg', 'veg', 'ブロッコリー', '06264', 80, 100, array['ブロッコリー']::text[], false),
    ('chicken-broccoli-any', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('chicken-broccoli-any', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('chicken-broccoli-any', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('low-oil-chicken', 'protein', 'protein', '鶏むね肉', '11220', 160, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('low-oil-chicken', 'protein', 'protein', '鶏もも肉', '11224', 140, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('low-oil-chicken', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('low-oil-chicken', 'protein', 'protein', '牛こま', '11019', 120, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('low-oil-chicken', 'veg', 'veg', 'キャベツ', '06061', 60, 100, array['キャベツ']::text[], false),
    ('low-oil-chicken', 'veg', 'veg', '白菜', '06233', 70, 101, array['白菜','はくさい']::text[], false),
    ('low-oil-chicken', 'veg', 'veg', 'ピーマン', '06245', 50, 102, array['ピーマン']::text[], false),
    ('low-oil-chicken', 'veg', 'veg', 'もやし', '06291', 60, 103, array['もやし']::text[], false),
    ('low-oil-chicken', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 200, array['しょうゆ','醤油']::text[], true),
    ('low-oil-chicken', 'mirin', 'seasoning', 'みりん', '16025', 8, 300, array['みりん','本みりん']::text[], true),
    ('low-oil-chicken', 'salt', 'seasoning', '塩', '17012', 1, 400, array['塩','食塩']::text[], true),
    ('hearty-don', 'protein', 'protein', '鶏むね肉', '11220', 220, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('hearty-don', 'protein', 'protein', '鶏もも肉', '11224', 180, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('hearty-don', 'protein', 'protein', '豚こま', '11115', 160, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('hearty-don', 'protein', 'protein', '牛こま', '11019', 150, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('hearty-don', 'egg', 'egg', '卵', '12004', 100, 100, array['卵','たまご','玉子']::text[], false),
    ('hearty-don', 'rice', 'staple', 'ごはん', '01088', 280, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('hearty-don', 'oil', 'oil', 'サラダ油', '14006', 12, 300, array['サラダ油','油']::text[], true),
    ('hearty-don', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 400, array['しょうゆ','醤油']::text[], true),
    ('hearty-don', 'salt', 'seasoning', '塩', '17012', 1, 500, array['塩','食塩']::text[], true),
    ('pork-cabbage-rice', 'protein', 'protein', '豚こま', '11115', 120, 0, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('pork-cabbage-rice', 'veg', 'veg', 'キャベツ', '06061', 80, 100, array['キャベツ']::text[], false),
    ('pork-cabbage-rice', 'onion', 'veg', '玉ねぎ', '06153', 50, 200, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('pork-cabbage-rice', 'rice', 'staple', 'ごはん', '01088', 180, 300, array['ごはん','ご飯','白米','お米']::text[], true),
    ('pork-cabbage-rice', 'oil', 'oil', 'サラダ油', '14006', 8, 400, array['サラダ油','油']::text[], true),
    ('pork-cabbage-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 500, array['しょうゆ','醤油']::text[], true),
    ('pork-cabbage-rice', 'mirin', 'seasoning', 'みりん', '16025', 8, 600, array['みりん','本みりん']::text[], true),
    ('chicken-onion-rice', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chicken-onion-rice', 'onion', 'veg', '玉ねぎ', '06153', 70, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('chicken-onion-rice', 'rice', 'staple', 'ごはん', '01088', 170, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('chicken-onion-rice', 'oil', 'oil', 'サラダ油', '14006', 10, 300, array['サラダ油','油']::text[], true),
    ('chicken-onion-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 400, array['しょうゆ','醤油']::text[], true),
    ('chicken-onion-rice', 'mirin', 'seasoning', 'みりん', '16025', 8, 500, array['みりん','本みりん']::text[], true),
    ('chicken-spinach-rice', 'protein', 'protein', '鶏むね肉', '11220', 150, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chicken-spinach-rice', 'veg', 'veg', 'ほうれん草', '06267', 60, 100, array['ほうれん草','ほうれんそう']::text[], false),
    ('chicken-spinach-rice', 'rice', 'staple', 'ごはん', '01088', 180, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('chicken-spinach-rice', 'oil', 'oil', 'サラダ油', '14006', 10, 300, array['サラダ油','油']::text[], true),
    ('chicken-spinach-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('chicken-spinach-rice', 'mirin', 'seasoning', 'みりん', '16025', 8, 500, array['みりん','本みりん']::text[], true),
    ('tofu-rice', 'protein', 'protein', '木綿豆腐', '04032', 200, 0, array['木綿豆腐','豆腐']::text[], false),
    ('tofu-rice', 'rice', 'staple', 'ごはん', '01088', 150, 100, array['ごはん','ご飯','白米','お米']::text[], true),
    ('tofu-rice', 'oil', 'oil', 'サラダ油', '14006', 4, 200, array['サラダ油','油']::text[], true),
    ('tofu-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('tofu-rice', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('tofu-rice', 'sugar', 'seasoning', '砂糖', '03003', 4, 500, array['砂糖']::text[], true),
    ('natto-egg-rice', 'protein', 'protein', '納豆', '04046', 60, 0, array['納豆']::text[], false),
    ('natto-egg-rice', 'egg', 'egg', '卵', '12004', 50, 100, array['卵','たまご','玉子']::text[], false),
    ('natto-egg-rice', 'rice', 'staple', 'ごはん', '01088', 140, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('natto-egg-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 300, array['しょうゆ','醤油']::text[], true),
    ('natto-egg-rice', 'salt', 'seasoning', '塩', '17012', 1, 400, array['塩','食塩']::text[], true),
    ('salmon-cabbage-rice', 'protein', 'protein', '鮭', '10134', 140, 0, array['鮭','さけ','サーモン','しろさけ']::text[], false),
    ('salmon-cabbage-rice', 'veg', 'veg', 'キャベツ', '06061', 70, 100, array['キャベツ']::text[], false),
    ('salmon-cabbage-rice', 'rice', 'staple', 'ごはん', '01088', 120, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('salmon-cabbage-rice', 'oil', 'oil', 'サラダ油', '14006', 8, 300, array['サラダ油','油']::text[], true),
    ('salmon-cabbage-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('salmon-cabbage-rice', 'mirin', 'seasoning', 'みりん', '16025', 6, 500, array['みりん','本みりん']::text[], true),
    ('salmon-cabbage-rice', 'sugar', 'seasoning', '砂糖', '03003', 2, 600, array['砂糖']::text[], true),
    ('cabbage-egg', 'egg', 'egg', '卵', '12004', 50, 0, array['卵','たまご','玉子']::text[], false),
    ('cabbage-egg', 'veg', 'veg', 'キャベツ', '06061', 80, 100, array['キャベツ']::text[], false),
    ('cabbage-egg', 'oil', 'oil', 'サラダ油', '14006', 3, 200, array['サラダ油','油']::text[], true),
    ('cabbage-egg', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('cabbage-egg', 'mirin', 'seasoning', 'みりん', '16025', 12, 400, array['みりん','本みりん']::text[], true),
    ('cabbage-egg', 'salt', 'seasoning', '塩', '17012', 1, 500, array['塩','食塩']::text[], true),
    ('chicken-potato', 'protein', 'protein', '鶏むね肉', '11220', 160, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chicken-potato', 'potato', 'veg', 'じゃがいも', '02017', 180, 100, array['じゃがいも','ジャガイモ','ポテト']::text[], false),
    ('chicken-potato', 'onion', 'veg', '玉ねぎ', '06153', 60, 200, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('chicken-potato', 'dashi', 'seasoning', '顆粒だし', '17028', 8, 300, array['顆粒だし','だし','和風だし']::text[], true),
    ('chicken-potato', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('chicken-potato', 'mirin', 'seasoning', 'みりん', '16025', 12, 500, array['みりん','本みりん']::text[], true),
    ('chicken-potato', 'sugar', 'seasoning', '砂糖', '03003', 10, 600, array['砂糖']::text[], true),
    ('many-bowl', 'protein', 'protein', '鶏むね肉', '11220', 160, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('many-bowl', 'veg', 'veg', 'キャベツ', '06061', 70, 100, array['キャベツ']::text[], false),
    ('many-bowl', 'egg', 'egg', '卵', '12004', 50, 200, array['卵','たまご','玉子']::text[], false),
    ('many-bowl', 'rice', 'staple', 'ごはん', '01088', 200, 300, array['ごはん','ご飯','白米','お米']::text[], true),
    ('many-bowl', 'oil', 'oil', 'サラダ油', '14006', 12, 400, array['サラダ油','油']::text[], true),
    ('many-bowl', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 500, array['しょうゆ','醤油']::text[], true),
    ('many-bowl', 'mirin', 'seasoning', 'みりん', '16025', 8, 600, array['みりん','本みりん']::text[], true),
    ('pork-only-rice', 'protein', 'protein', '豚こま', '11115', 120, 0, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('pork-only-rice', 'rice', 'staple', 'ごはん', '01088', 180, 100, array['ごはん','ご飯','白米','お米']::text[], true),
    ('pork-only-rice', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('pork-only-rice', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 300, array['しょうゆ','醤油']::text[], true),
    ('pork-only-rice', 'mirin', 'seasoning', 'みりん', '16025', 10, 400, array['みりん','本みりん']::text[], true),
    ('pork-only-rice', 'sugar', 'seasoning', '砂糖', '03003', 6, 500, array['砂糖']::text[], true),
    ('avoid-oil-chicken', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('avoid-oil-chicken', 'onion', 'veg', '玉ねぎ', '06153', 40, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('avoid-oil-chicken', 'egg', 'egg', '卵', '12004', 50, 200, array['卵','たまご','玉子']::text[], false),
    ('avoid-oil-chicken', 'rice', 'staple', 'ごはん', '01088', 170, 300, array['ごはん','ご飯','白米','お米']::text[], true),
    ('avoid-oil-chicken', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 400, array['顆粒だし','だし','和風だし']::text[], true),
    ('avoid-oil-chicken', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 500, array['しょうゆ','醤油']::text[], true),
    ('avoid-oil-chicken', 'mirin', 'seasoning', 'みりん', '16025', 10, 600, array['みりん','本みりん']::text[], true),
    ('negi-salt', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('negi-salt', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('negi-salt', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('negi-salt', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('negi-salt', 'protein', 'protein', '厚揚げ', '04039', 80, 4, array['厚揚げ','あつあげ']::text[], false),
    ('negi-salt', 'veg', 'veg', 'ねぎ', '06226', 50, 100, array['ねぎ','長ねぎ','ネギ']::text[], false),
    ('negi-salt', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('negi-salt', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 300, array['しょうゆ','醤油']::text[], true),
    ('negi-salt', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('negi-salt', 'salt', 'seasoning', '塩', '17012', 1, 500, array['塩','食塩']::text[], true),
    ('chuka-don', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chuka-don', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('chuka-don', 'protein', 'protein', '豚こま', '11115', 110, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('chuka-don', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('chuka-don', 'veg', 'veg', 'キャベツ', '06061', 70, 100, array['キャベツ']::text[], false),
    ('chuka-don', 'veg', 'veg', '白菜', '06233', 90, 101, array['白菜','はくさい']::text[], false),
    ('chuka-don', 'veg', 'veg', 'ピーマン', '06245', 60, 102, array['ピーマン']::text[], false),
    ('chuka-don', 'veg', 'veg', 'もやし', '06291', 70, 103, array['もやし']::text[], false),
    ('chuka-don', 'rice', 'staple', 'ごはん', '01088', 180, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('chuka-don', 'oil', 'oil', 'サラダ油', '14006', 8, 300, array['サラダ油','油']::text[], true),
    ('chuka-don', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 400, array['しょうゆ','醤油']::text[], true),
    ('chuka-don', 'mirin', 'seasoning', 'みりん', '16025', 8, 500, array['みりん','本みりん']::text[], true),
    ('chuka-don', 'sugar', 'seasoning', '砂糖', '03003', 6, 600, array['砂糖']::text[], true),
    ('yurinchi', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('yurinchi', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('yurinchi', 'onion', 'veg', '玉ねぎ', '06153', 60, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('yurinchi', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('yurinchi', 'vinegar', 'seasoning', '酢', '17015', 12, 300, array['酢','お酢']::text[], true),
    ('yurinchi', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 400, array['しょうゆ','醤油']::text[], true),
    ('yurinchi', 'sugar', 'seasoning', '砂糖', '03003', 8, 500, array['砂糖']::text[], true),
    ('tofu-chuka', 'protein', 'protein', '木綿豆腐', '04032', 180, 0, array['木綿豆腐','豆腐']::text[], false),
    ('tofu-chuka', 'veg', 'veg', 'キャベツ', '06061', 80, 100, array['キャベツ']::text[], false),
    ('tofu-chuka', 'veg', 'veg', '白菜', '06233', 100, 101, array['白菜','はくさい']::text[], false),
    ('tofu-chuka', 'veg', 'veg', 'ピーマン', '06245', 60, 102, array['ピーマン']::text[], false),
    ('tofu-chuka', 'veg', 'veg', 'もやし', '06291', 80, 103, array['もやし']::text[], false),
    ('tofu-chuka', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('tofu-chuka', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('tofu-chuka', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('negi-fry', 'protein', 'protein', '鶏むね肉', '11220', 130, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('negi-fry', 'protein', 'protein', '鶏もも肉', '11224', 120, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('negi-fry', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('negi-fry', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('negi-fry', 'veg', 'veg', 'ねぎ', '06226', 50, 100, array['ねぎ','長ねぎ','ネギ']::text[], false),
    ('negi-fry', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('negi-fry', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 300, array['しょうゆ','醤油']::text[], true),
    ('negi-fry', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('tuna-chuka', 'protein', 'protein', 'ツナ', '10263', 80, 0, array['ツナ','ツナ缶']::text[], false),
    ('tuna-chuka', 'veg', 'veg', 'キャベツ', '06061', 80, 100, array['キャベツ']::text[], false),
    ('tuna-chuka', 'veg', 'veg', '白菜', '06233', 100, 101, array['白菜','はくさい']::text[], false),
    ('tuna-chuka', 'veg', 'veg', 'ピーマン', '06245', 60, 102, array['ピーマン']::text[], false),
    ('tuna-chuka', 'veg', 'veg', 'もやし', '06291', 80, 103, array['もやし']::text[], false),
    ('tuna-chuka', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('tuna-chuka', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('tuna-chuka', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('egg-tomato-soup', 'protein', 'egg', '卵', '12004', 50, 0, array['卵','たまご','玉子']::text[], false),
    ('egg-tomato-soup', 'veg', 'veg', 'トマト', '06182', 80, 100, array['トマト']::text[], false),
    ('egg-tomato-soup', 'dashi', 'seasoning', '顆粒だし', '17028', 6, 200, array['顆粒だし','だし','和風だし']::text[], true),
    ('egg-tomato-soup', 'miso', 'seasoning', '味噌', '17045', 8, 300, array['味噌','みそ']::text[], true),
    ('egg-tomato-soup', 'soy', 'seasoning', 'しょうゆ', '17007', 4, 400, array['しょうゆ','醤油']::text[], true),
    ('chuka-steam', 'protein', 'protein', '鶏むね肉', '11220', 160, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('chuka-steam', 'protein', 'protein', '鶏もも肉', '11224', 150, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('chuka-steam', 'protein', 'protein', '豚こま', '11115', 140, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('chuka-steam', 'protein', 'protein', '牛こま', '11019', 120, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('chuka-steam', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 100, array['しょうゆ','醤油']::text[], true),
    ('chuka-steam', 'mirin', 'seasoning', 'みりん', '16025', 8, 200, array['みりん','本みりん']::text[], true),
    ('chuka-steam', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('hakusai-fry', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('hakusai-fry', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('hakusai-fry', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('hakusai-fry', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('hakusai-fry', 'veg', 'veg', '白菜', '06233', 120, 100, array['白菜','はくさい']::text[], false),
    ('hakusai-fry', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('hakusai-fry', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 300, array['しょうゆ','醤油']::text[], true),
    ('hakusai-fry', 'mirin', 'seasoning', 'みりん', '16025', 8, 400, array['みりん','本みりん']::text[], true),
    ('grill', 'protein', 'protein', '鶏むね肉', '11220', 160, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('grill', 'protein', 'protein', '鶏もも肉', '11224', 150, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('grill', 'protein', 'protein', '豚こま', '11115', 140, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('grill', 'protein', 'protein', '牛こま', '11019', 130, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('grill', 'oil', 'oil', 'サラダ油', '14006', 6, 100, array['サラダ油','油']::text[], true),
    ('grill', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 200, array['しょうゆ','醤油']::text[], true),
    ('grill', 'mirin', 'seasoning', 'みりん', '16025', 6, 300, array['みりん','本みりん']::text[], true),
    ('grill', 'salt', 'seasoning', '塩', '17012', 1, 400, array['塩','食塩']::text[], true),
    ('grill', 'pepper', 'seasoning', 'こしょう', '17063', 1, 500, array['こしょう','胡椒','コショウ']::text[], true),
    ('tuna-onion-pasta', 'protein', 'protein', 'ツナ', '10263', 70, 0, array['ツナ','ツナ缶']::text[], false),
    ('tuna-onion-pasta', 'veg', 'veg', '玉ねぎ', '06153', 70, 100, array['玉ねぎ','たまねぎ','タマネギ']::text[], false),
    ('tuna-onion-pasta', 'pasta', 'staple', 'スパゲティ', '01064', 180, 200, array['スパゲティ','パスタ']::text[], false),
    ('tuna-onion-pasta', 'oil', 'oil', 'サラダ油', '14006', 6, 300, array['サラダ油','油']::text[], true),
    ('tuna-onion-pasta', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 400, array['しょうゆ','醤油']::text[], true),
    ('tuna-onion-pasta', 'pepper', 'seasoning', 'こしょう', '17063', 1, 500, array['こしょう','胡椒','コショウ']::text[], true),
    ('broccoli-grill', 'protein', 'protein', '鶏むね肉', '11220', 150, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('broccoli-grill', 'protein', 'protein', '鶏もも肉', '11224', 140, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('broccoli-grill', 'protein', 'protein', '豚こま', '11115', 130, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('broccoli-grill', 'protein', 'protein', '牛こま', '11019', 120, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('broccoli-grill', 'veg', 'veg', 'ブロッコリー', '06264', 80, 100, array['ブロッコリー']::text[], false),
    ('broccoli-grill', 'oil', 'oil', 'サラダ油', '14006', 6, 200, array['サラダ油','油']::text[], true),
    ('broccoli-grill', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 300, array['しょうゆ','醤油']::text[], true),
    ('broccoli-grill', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('broccoli-grill', 'salt', 'seasoning', '塩', '17012', 1, 500, array['塩','食塩']::text[], true),
    ('broccoli-grill', 'pepper', 'seasoning', 'こしょう', '17063', 1, 600, array['こしょう','胡椒','コショウ']::text[], true),
    ('salmon-tomato-pasta', 'protein', 'protein', '鮭', '10134', 100, 0, array['鮭','さけ','サーモン','しろさけ']::text[], false),
    ('salmon-tomato-pasta', 'veg', 'veg', 'トマト', '06182', 80, 100, array['トマト']::text[], false),
    ('salmon-tomato-pasta', 'pasta', 'staple', 'スパゲティ', '01064', 170, 200, array['スパゲティ','パスタ']::text[], false),
    ('salmon-tomato-pasta', 'oil', 'oil', 'サラダ油', '14006', 6, 300, array['サラダ油','油']::text[], true),
    ('salmon-tomato-pasta', 'soy', 'seasoning', 'しょうゆ', '17007', 6, 400, array['しょうゆ','醤油']::text[], true),
    ('salmon-tomato-pasta', 'pepper', 'seasoning', 'こしょう', '17063', 1, 500, array['こしょう','胡椒','コショウ']::text[], true),
    ('tuna-sandwich', 'protein', 'protein', 'ツナ', '10263', 70, 0, array['ツナ','ツナ缶']::text[], false),
    ('tuna-sandwich', 'bread', 'staple', '食パン', '01026', 70, 100, array['食パン','パン']::text[], false),
    ('tuna-sandwich', 'butter', 'oil', 'バター', '14017', 5, 200, array['バター']::text[], true),
    ('tuna-sandwich', 'salt', 'seasoning', '塩', '17012', 1, 300, array['塩','食塩']::text[], true),
    ('tuna-sandwich', 'pepper', 'seasoning', 'こしょう', '17063', 1, 400, array['こしょう','胡椒','コショウ']::text[], true),
    ('ethnic-tomato', 'protein', 'protein', '鶏むね肉', '11220', 140, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('ethnic-tomato', 'protein', 'protein', '鶏もも肉', '11224', 130, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('ethnic-tomato', 'protein', 'protein', '豚こま', '11115', 120, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('ethnic-tomato', 'protein', 'protein', '牛こま', '11019', 110, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('ethnic-tomato', 'veg', 'veg', 'トマト', '06182', 90, 100, array['トマト']::text[], false),
    ('ethnic-tomato', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('ethnic-tomato', 'soy', 'seasoning', 'しょうゆ', '17007', 8, 300, array['しょうゆ','醤油']::text[], true),
    ('ethnic-tomato', 'mirin', 'seasoning', 'みりん', '16025', 6, 400, array['みりん','本みりん']::text[], true),
    ('tuna-ethnic', 'protein', 'protein', 'ツナ', '10263', 80, 0, array['ツナ','ツナ缶']::text[], false),
    ('tuna-ethnic', 'veg', 'veg', 'キャベツ', '06061', 90, 100, array['キャベツ']::text[], false),
    ('tuna-ethnic', 'oil', 'oil', 'サラダ油', '14006', 8, 200, array['サラダ油','油']::text[], true),
    ('tuna-ethnic', 'miso', 'seasoning', '味噌', '17045', 10, 300, array['味噌','みそ']::text[], true),
    ('tuna-ethnic', 'sugar', 'seasoning', '砂糖', '03003', 6, 400, array['砂糖']::text[], true),
    ('tuna-ethnic', 'sake', 'seasoning', '料理酒', '17138', 8, 500, array['料理酒','酒']::text[], true),
    ('garlic-don', 'protein', 'protein', '鶏むね肉', '11220', 120, 0, array['鶏むね肉','鶏むね','鶏胸肉','鶏肉']::text[], false),
    ('garlic-don', 'protein', 'protein', '鶏もも肉', '11224', 110, 1, array['鶏もも肉','鶏もも','鶏モモ']::text[], false),
    ('garlic-don', 'protein', 'protein', '豚こま', '11115', 110, 2, array['豚こま','豚こま切れ','豚コマ','豚肉']::text[], false),
    ('garlic-don', 'protein', 'protein', '牛こま', '11019', 100, 3, array['牛こま','牛もも','牛肉']::text[], false),
    ('garlic-don', 'ginger', 'other', 'にんにく', '06223', 20, 100, array['にんにく','ニンニク']::text[], false),
    ('garlic-don', 'rice', 'staple', 'ごはん', '01088', 180, 200, array['ごはん','ご飯','白米','お米']::text[], true),
    ('garlic-don', 'oil', 'oil', 'サラダ油', '14006', 8, 300, array['サラダ油','油']::text[], true),
    ('garlic-don', 'soy', 'seasoning', 'しょうゆ', '17007', 10, 400, array['しょうゆ','醤油']::text[], true),
    ('garlic-don', 'mirin', 'seasoning', 'みりん', '16025', 8, 500, array['みりん','本みりん']::text[], true);
end $$;

